// ══════════════════════════════════════════════════════════════════
//  CONTENUTI COMPLETI — tutti gli articoli copiati dal progetto
//  Nessuna chiamata esterna: tutto il testo è hardcodato qui.
// ══════════════════════════════════════════════════════════════════
const CONTENT = {

  0: `<p><strong>OLTRECONFINE</strong> è stato un progetto culturale pluriennale sulla Grande Guerra nato dall'esigenza di creare, in un'area che all'epoca era attraversata da un confine, un immaginario storico comune e condiviso di alcuni avvenimenti significativi, nella pluralità dei punti di vista e nel superamento di alcune distorsioni e mistificazioni intercorse negli anni successivi.</p>
<p>Il progetto ha preso avvio nel 2015 su iniziativa e coordinamento del Comune di Palmanova, capofila dell'iniziativa, nell'ambito delle celebrazioni per i cento anni dalla Prima Guerra mondiale, e si è concluso nel 2019–2020 con la fase di raccolta documentale sull'esperienza maturata.</p>
<p>OLTRECONFINE è stato un progetto "dal basso", articolato in più fasi per ogni annualità: la prima prevedeva incontri con la cittadinanza in serate-forum animate da cori, bande e gruppi culturali locali, aperte all'intervento di esperti storici e semplici cittadini che hanno portato memorie, storie e materiali anche inediti; nella seconda fase il direttore artistico ha rielaborato tutto questo in forma drammaturgica attraverso laboratori teatrali cui hanno partecipato i cittadini stessi; infine il tutto è stato "restituito" da questi stessi cittadini in forma di spettacolo, replicato in ogni Comune partecipante.</p>
<p>I Comuni coinvolti sono stati 17: Palmanova (capofila), Aiello del Friuli, Bagnaria Arsa, Bicinicco, Campolongo Tapogliano, Castions di Strada, Chiopris Viscone, Gonars, Medea, Romans D'Isonzo, Ruda, San Vito al Torre, Santa Maria La Longa, Torviscosa, Trivignano Udinese, Villesse, Visco.</p>
<p>Ora quel percorso è <strong>raccolto in una pubblicazione in tre volumi</strong> – ciascuno dedicato ad uno degli anni di guerra – che si può acquistare in formato cartaceo contattando l'associazione Cikale Operose: cikaleoperose@gmail.com.</p>
<p>«Il volume OLTRECONFINE intende raccontare storie di uomini e donne, la gente comune di paese all'epoca della Grande Guerra – evidenziano <strong>Francesco Accomando</strong>, <strong>Giampaolo Fioretti</strong> e <strong>Gianni Russo</strong> dello staff di direzione – nell'idea di recuperare brandelli di storia anche volutamente dimenticati, guardando anche al nostro presente, nella consapevolezza che la memoria storica può aiutare a comprendere altri conflitti e altri confini che oggi si presentano sul nostro orizzonte».</p>
<p>«La consapevolezza della Storia, originatasi sui drammi delle popolazioni, risulta essere l'unico strumento in grado di incidere sul presente – rimarcano il sindaco di Palmanova <strong>Francesco Martines</strong> e il vicesindaco <strong>Adriana Danielis</strong> – I destinatari principali del progetto sono le nuove generazioni che, attraverso la scuola, saranno i depositari della Memoria di questi luoghi».</p>`,

  1: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/09/OLTRECONFINE-2018-passeggiata-teatrale-Ara-Pacis-Medea-1.jpg" alt="Passeggiata teatrale Ara Pacis Medea" loading="lazy">
<p>«Qui finisce la nostra "storia di un confine". Ma questo momento è solo un fatto transitorio, un passaggio, attraverso una soglia che porterà a nuovi confini. Abbiamo raccontato una parte importante della nostra storia, come abbiamo saputo, l'abbiamo raccontata come abbiamo potuto, nel tempo fugace di una rappresentazione. Ora, per favore, non lasciateci qui. Portateci con voi, nel vostro cuore e nella vostra immaginazione. E il ricordo di noi e di quello che vi abbiamo raccontato, donne e uomini che hanno vissuto, sia memoria, che vive nel presente, e così diviene presenza».</p>
<p>Si è conclusa con queste parole toccanti la serata finale del 29 agosto all'<strong>Ara Pacis Mundi di Medea</strong> del progetto <strong>OLTRECONFINE</strong> sulla Grande Guerra. Oltre 150 spettatori hanno accompagnato gli attori nell'ultima passeggiata teatrale dell'edizione 2018, una processione laica intitolata "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>".</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/09/OLTRECONFINE-2018-passeggiata-teatrale-Ara-Pacis-Medea-2.jpg" alt="Passeggiata teatrale conclusiva Medea" loading="lazy">
<p>Per quasi due mesi l'evento teatrale – diretto da <strong>Francesco Accomando</strong> con il coordinamento di <strong>Giampaolo Fioretti</strong>, <strong>Giovanni Russo</strong> e l'organizzazione di Cikale Operose – ha coinvolto <strong>più di mille persone</strong> all'interno delle comunità dei paesi toccati dalla passeggiata. Gli attori protagonisti sono stati: Silvio Basile, Anna Bolognese, Bruno Chiaranti, Franco D'Ambrosio, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Sandra Mansutti, Alessio Michelin, Romeo Mischis, Andrea Nicola, Massimiliana Olivo, Renato Sclauzero, Bruno Tomasin, Francesco Ursella e Fabio Vidoz.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/08/20180829-001-ara-pacis.jpg" alt="Ara Pacis Medea 29 agosto 2018" loading="lazy">
<p>«Un percorso lungo tre anni che ha saputo coinvolgere molte persone legate da un passato comune – sottolinea la vicesindaco di Palmanova <strong>Adriana Danielis</strong> – Il lavoro di molti appassionati e studiosi di storia è riuscito a far emergere fatti e memorie spesso sepolte, che ora possono diventare patrimonio comune».</p>
<p>«Qui ora finisce Oltreconfine – ha dichiarato al termine della salita a Medea <strong>Francesco Accomando</strong> – Davanti a questo tempio noi ricordiamo i caduti della Grande Guerra, militari e civili. Ricordiamo i caduti ma ricordiamo anche quelli che non sono caduti, i sopravvissuti nonostante le mutilazioni del corpo, della mente, del cuore. Noi siamo i loro discendenti».</p>`,

  2: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/08/20180829-001-ara-pacis.jpg" alt="Ara Pacis Medea passeggiata teatrale" loading="lazy">
<p>Un evento straordinario, carico di emozione e poesia, conclude il percorso triennale del progetto <strong>OLTRECONFINE</strong> che ha coinvolto 17 Comuni del Friuli Venezia Giulia con capofila Palmanova.</p>
<p>La "passeggiata teatrale" di <strong>OLTRECONFINE 1918/2018</strong> sale fino all'<strong>Ara Pacis di MEDEA</strong> mercoledì 29 agosto con una sorta di processione laica dedicata alla memoria della prima guerra mondiale. Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prende le mosse alle 20.15 dal colle di Medea e si sviluppa in salita verso il monumento avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/08/OLTRECONFINE-2018-passeggiata-teatrale-col.jpg" alt="Oltreconfine 2018 passeggiata teatrale" loading="lazy">
<p>«Il cammino ricorda i tanti che all'epoca della Grande Guerra hanno attraversato il territorio di confine del Friuli – spiega il direttore artistico <strong>Francesco Accomando</strong> – Migliaia e migliaia da Caporetto a dopo la fine della guerra, truppe in avanzata e in ritirata, militari in rientro dal fronte per la licenza, prigionieri ed ex prigionieri di ritorno, civili fuggiaschi, profughi, deportati… Così lo spettacolo ha la forma del camminare, una sorta di rituale laico che coinvolge attori e pubblico nell'atto del ricordare e nello stesso tempo è l'invito a un cammino collettivo per costruire una pace forse mai raggiungibile nella sua pienezza».</p>
<p>Nel titolo c'è anche un paradosso: «ci racconta come solo i morti hanno trovato finalmente la pace alle loro sofferenze, mentre per i vivi la guerra della miseria e della fame è continuata ben oltre il termine delle ostilità. Infine ai vivi è concesso il silenzio di una visita al camposanto, ma a loro appartiene anche il silenzio su tutto quello che non hanno voluto o potuto raccontare di quei giorni tremendi».</p>
<p><strong>Per informazioni: tel. 339.4238228</strong></p>`,

  3: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/07/20180711-001-castions.jpg" alt="Castions di Strada passeggiata teatrale" loading="lazy">
<p>Rinviata per maltempo a luglio, la "passeggiata teatrale" nel progetto <strong>OLTRECONFINE 1918/2018</strong> incontra la comunità di <strong>CASTIONS DI STRADA</strong> giovedì 23 agosto. Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 20.30 dalla Chiesa di S. Maria (via del Riposo) e attraverserà strade e campagne avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/08/OLTRECONFINE-2018-passeggiata-teatrale-col2.jpg" alt="Oltreconfine 2018 passeggiata teatrale" loading="lazy">
<p>«Il cammino ricorda i tanti che all'epoca della Grande Guerra hanno attraversato il territorio di confine del Friuli – spiega il direttore artistico <strong>Francesco Accomando</strong> – Migliaia e migliaia da Caporetto a dopo la fine della guerra, truppe in avanzata e in ritirata, militari in rientro dal fronte per la licenza, prigionieri ed ex prigionieri di ritorno, civili fuggiaschi, profughi, deportati… Così lo spettacolo ha la forma del camminare, una sorta di rituale laico che coinvolge attori e pubblico nell'atto del ricordare».</p>
<p>La partecipazione alla passeggiata teatrale è gratuita. L'organizzazione consiglia abbigliamento e scarpe comodi.<br><strong>Per informazioni: tel. 339.4238228</strong></p>`,

  4: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/08/20180809-001-s.maria-mereto.jpg" alt="S. Maria la Longa passeggiata teatrale" loading="lazy">
<p>Si avvia alla conclusione il lungo percorso della "passeggiata teatrale" nel progetto <strong>OLTRECONFINE 1918/2018</strong>, che giovedì 9 agosto arriva a <strong>S. MARIA LA LONGA</strong>. Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 20.45 dall'ex convento delle Clarisse in località Mereto di Capitolo e attraverserà strade e argini avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/08/OLTRECONFINE-2018-passeggiata-teatrale-col.jpg" alt="Oltreconfine 2018 passeggiata teatrale" loading="lazy">
<p>L'intera comunità è invitata a partecipare, per vivere l'emozione di una memoria lontana cent'anni eppure ancora viva nelle famiglie che hanno sofferto il dramma su un confine che è divenuto un fronte cruciale per le sorti della Prima Guerra Mondiale.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita.<br><strong>Per informazioni: tel. 339.4238228</strong></p>`,

  5: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/08/OLTRECONFINE-2018-passeggiata-teatrale.jpg" alt="Torviscosa passeggiata teatrale" loading="lazy">
<p>Una nuova tappa nella "passeggiata teatrale" del progetto <strong>OLTRECONFINE 1918/2018</strong>, che lunedì 6 agosto arriva a <strong>TORVISCOSA</strong>. Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 20.45 dalla Chiesa dei SS. Pietro e Paolo in località Malisana e attraverserà strade e argini avvolgendo il filo rosso della memoria.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/08/OLTRECONFINE-2018-passeggiata-teatrale-luna.jpg" alt="Passeggiata teatrale notturna" loading="lazy">
<p>L'intera comunità è invitata a partecipare, per vivere l'emozione di una memoria lontana cent'anni eppure ancora viva nelle famiglie che hanno sofferto il dramma su un confine che è divenuto un fronte cruciale per le sorti della Prima Guerra Mondiale.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita.<br><strong>Per informazioni: tel. 339.4238228</strong></p>`,

  6: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/08/OLTRECONFINE-passeggiata-teatrale-Villesse-1.jpg" alt="Romans d'Isonzo passeggiata teatrale" loading="lazy">
<p>Si recupera venerdì 3 agosto (dopo il rinvio di giugno) la "passeggiata teatrale" del progetto <strong>OLTRECONFINE 1918/2018</strong> a <strong>Romans d'Isonzo</strong>. Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 20.45 dalla località Versa (via Lauretana) e attraverserà strade e argini avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>L'evento teatrale si configura come una processione laica, sulla quale il direttore artistico <strong>Francesco Accomando</strong>, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita.<br><strong>Per informazioni: tel. 339.4238228</strong></p>`,


  10: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/07/OLTRECONFINE-Bicinicco-passeggiata-teatrale.jpg" alt="Ruda passeggiata teatrale" loading="lazy">
<p>Prosegue l'intenso percorso della "passeggiata teatrale" nel progetto <strong>OLTRECONFINE 1918/2018</strong>, che lunedì 23 luglio fa tappa a <strong>RUDA</strong>. Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 21 da Piazza Libertà e attraverserà strade e campagne avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>L'evento teatrale si presenta come una processione laica, sulla quale il direttore artistico <strong>Francesco Accomando</strong>, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita.<br><strong>Per informazioni: tel. 339.4238228</strong></p>`,

  11: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/07/OLTRECONFINE-villesse.jpg" alt="Villesse passeggiata teatrale" loading="lazy">
<p>Prosegue l'intenso percorso della "passeggiata teatrale" nel progetto <strong>OLTRECONFINE 1918/2018</strong>, che mercoledì 18 luglio fa tappa a <strong>VILLESSE</strong>. Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 21 dalla Cappella Beato Carlo d'Asburgo e attraverserà strade e campagne avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>L'evento teatrale si presenta come una processione laica, sulla quale il direttore artistico <strong>Francesco Accomando</strong>, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/07/OLTRECONFINE-2018-passeggiata-teatrale-Campolongo-Tapogliano.jpg" alt="Passeggiata teatrale Campolongo" loading="lazy">
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita.<br><strong>Per informazioni: tel. 339.4238228</strong></p>`,

  12: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/07/20180716-001-s.vito_.jpg" alt="San Vito al Torre passeggiata teatrale" loading="lazy">
<p>Arriva a metà strada l'intenso percorso della "passeggiata teatrale" nel progetto <strong>OLTRECONFINE 1918/2018</strong>, che lunedì 13 luglio fa tappa a <strong>San Vito al Torre</strong>. Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 21 dalla Chiesa dei SS. Vito e Modesto e attraverserà strade e campagne avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/07/oltreconfine-passeggiata-teatrale-Visco-1.jpg" alt="Passeggiata teatrale Visco" loading="lazy">
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita.<br><strong>Per informazioni: tel. 339.4238228</strong></p>`,


  13: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/07/20180711-001-castions.jpg" alt="Castions di Strada passeggiata teatrale rinviata" loading="lazy">
<p><strong>L'EVENTO È STATO RINVIATO PER MALTEMPO</strong></p>
<p>Arriva quasi a metà l'intenso percorso compiuto dalla "passeggiata teatrale" nel progetto <strong>OLTRECONFINE 1918/2018</strong>, che mercoledì 11 luglio fa tappa a <strong>Castions di Strada</strong>. Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 21 dalla Chiesa di S. Maria (via del Riposo) e attraverserà strade e campagne avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/07/oltreconfine-passeggiata-teatrale-Gonars-3.jpg" alt="Passeggiata teatrale Gonars" loading="lazy">
<p>L'evento teatrale si presenta come una processione laica, sulla quale il direttore artistico <strong>Francesco Accomando</strong>, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita.<br><strong>Per informazioni: tel. 339.4238228</strong></p>`,

  14: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/07/oltreconfine-passeggiata-teatrale-Gonars-5.jpg" alt="Visco passeggiata teatrale" loading="lazy">
<p>Dopo le prime serate, l'intensa e coinvolgente "passeggiata teatrale" del progetto <strong>OLTRECONFINE 1918/2018</strong> fa tappa a <strong>Visco</strong>. Lunedì 9 luglio il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 21.00 da Piazza Ledra e attraverserà strade e campagne avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>L'evento teatrale si presenta come una processione laica, sulla quale il direttore artistico <strong>Francesco Accomando</strong>, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<p>«Il cammino ricorda i tanti che all'epoca della Grande Guerra, hanno attraversato il territorio di confine del Friuli – spiega il direttore artistico <strong>Francesco Accomando</strong> – Migliaia e migliaia da Caporetto a dopo la fine della guerra, truppe in avanzata e in ritirata, militari in rientro dal fronte per la licenza, prigionieri ed ex prigionieri di ritorno, civili fuggiaschi, profughi, deportati… Così lo spettacolo ha la forma del camminare, una sorta di rituale laico che coinvolge attori e pubblico nell'atto del ricordare».</p>
<p>La partecipazione alla passeggiata teatrale è gratuita.<br><strong>Per informazioni: tel. 339.4238228</strong></p>`,


  15: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/07/oltreconfine-bicinicco.jpg" alt="Bicinicco passeggiata teatrale" loading="lazy">
<p>Dopo le prime cinque tappe, l'intensa e coinvolgente "passeggiata teatrale" del progetto <strong>OLTRECONFINE 1918/2018</strong> fa tappa a <strong>Bicinicco</strong>. Mercoledì 4 luglio il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 21.15 dalla Chiesa di S. Giorgio e attraverserà strade e campagne avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/06/OLTRECONFINE-passeggiata-teatrale-1.jpg" alt="Passeggiata teatrale Gonars" loading="lazy">
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita.<br><strong>Per informazioni: tel. 339.4238228</strong></p>`,

  16: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/06/campolongo.jpg" alt="Campolongo Tapogliano passeggiata teatrale" loading="lazy">
<p>Dopo le prime tre tappe, l'intensa e coinvolgente "passeggiata teatrale" del progetto <strong>OLTRECONFINE 1918/2018</strong> arriva a <strong>Campolongo Tapogliano</strong>. Lunedì 2 luglio il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 21.15 dalla Chiesa di S. Maria Assunta in località Cavenzano e attraverserà strade e argini avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/06/OLTRECONFINE-passeggiata-teatrale-1.jpg" alt="Passeggiata teatrale" loading="lazy">
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita.<br><strong>Per informazioni: tel. 339.4238228</strong></p>`,

  17: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/06/OLTRECONFINE-passeggiata-teatrale-1.jpg" alt="Gonars passeggiata teatrale" loading="lazy">
<p>Dopo le prime tre tappe, l'intensa e coinvolgente "passeggiata teatrale" del progetto <strong>OLTRECONFINE 1918/2018</strong> arriva a <strong>Gonars</strong>. Mercoledì 27 giugno il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 21.15 dalla Scuola dell'Infanzia "Chiara e Federico" (via Molini) e attraverserà strade e argini avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<p>«Il cammino ricorda i tanti che all'epoca della Grande Guerra hanno attraversato il territorio di confine del Friuli – spiega <strong>Francesco Accomando</strong> – Migliaia e migliaia da Caporetto a dopo la fine della guerra, truppe in avanzata e in ritirata, militari in rientro dal fronte per la licenza, prigionieri ed ex prigionieri di ritorno, civili fuggiaschi, profughi, deportati. Così lo spettacolo ha la forma del camminare, una sorta di rituale laico che coinvolge attori e pubblico nell'atto del ricordare».</p>
<p>La partecipazione alla passeggiata teatrale è gratuita.<br><strong>Per informazioni: tel. 339.4238228</strong></p>`,


  18: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/06/romans-versa.jpg" alt="Romans d'Isonzo passeggiata teatrale" loading="lazy">
<p>Prosegue la "passeggiata teatrale" del progetto <strong>OLTRECONFINE 1918/2018</strong>. Lunedì 25 giugno la tappa attraversa <strong>Romans d'Isonzo</strong>. Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 21.15 dalla località Versa (via Lauretana) e attraverserà strade e argini avvolgendo il filo rosso della memoria.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita.<br><strong>Per informazioni: tel. 339.4238228</strong></p>`,

  19: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/06/chiopris.jpg" alt="Chiopris Viscone passeggiata teatrale" loading="lazy">
<p>Prosegue la "passeggiata teatrale" del progetto <strong>OLTRECONFINE 1918/2018</strong> che mercoledì 20 giugno fa tappa a <strong>Chiopris Viscone</strong>. Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 21.15 dalla Chiesa di S. Martino.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita.<br><strong>Per informazioni: tel. 339.4238228</strong></p>`,

  20: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/06/loggia-palma.jpg" alt="Palmanova Loggia di guardia Porta Aquileia" loading="lazy">
<p>Una intensa, coinvolgente "passeggiata teatrale" prende le mosse dalla <strong>Loggia di guardia di Porta Aquileia</strong> e attraversa le strade di <strong>Palmanova</strong> avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra. Prende avvio mercoledì 20 giugno (ore 21.15) nella città-fortezza il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>", una processione laica costruita dal regista <strong>Francesco Accomando</strong> a conclusione del progetto <strong>OLTRECONFINE 1918/2018</strong>.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/06/OLTRECONFINE-2017-restituzione-teatrale-Gonars-1-ph-G-Russo.jpg" alt="Restituzione teatrale 2017" loading="lazy">
<p>Dopo aver incontrato associazioni, scuole, famiglie, amministratori locali nei 17 comuni coinvolti, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> e il direttore artistico <strong>Accomando</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti nella costruzione di una restituzione drammaturgica delle memorie raccolte.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita.<br><strong>Per informazioni: tel. 339.4238228</strong></p>`,

  21: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2017/04/truppe-al-fronte.jpg" alt="Truppe al fronte Grande Guerra" loading="lazy">
<p>Una lunga, intensa, coinvolgente passeggiata teatrale attraverserà cittadine e paesi del Friuli avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>Si concluderà così il progetto <strong>OLTRECONFINE 1918/2018</strong> dedicato alle memorie della grande guerra sul confine italo austriaco. Dopo aver incontrato associazioni, scuole, famiglie, amministratori locali nei comuni coinvolti, i curatori dell'associazione <strong>Cikale Operose</strong> e il direttore artistico <strong>Francesco Accomando</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti nella costruzione di una restituzione drammaturgica delle memorie raccolte.</p>
<p>La passeggiata teatrale sarà intitolata "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" e muoverà i primi passi da Palmanova il 20 giugno 2018. Proseguirà poi con altre 16 tappe fino alla fine di agosto, con l'ultima replica e la salita all'<strong>Ara Pacis di Medea</strong>.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/06/OLTRECONFINE-2018-passeggiate-teatrali.jpg" alt="Calendario passeggiate teatrali 2018" loading="lazy">
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<p>«Il lavoro di questi tre anni ha coinvolto molte realtà territoriali che hanno saputo raccogliere l'eredità di esperienze e testimonianze tramandate di generazione in generazione, contribuendo a riportare alla luce una memoria comune».</p>
<p>La partecipazione è gratuita.<br><strong>Per informazioni: tel. 339.4238228</strong></p>`,


  22: `<p><strong>ROMANS D'ISONZO – 1 marzo 2018</strong></p>
<p>Serata intensa e densa di interventi a Romans d'Isonzo nella fase di incontro con le comunità del Friuli Venezia Giulia per il progetto <strong>OLTRECONFINE 1918/2018</strong>.</p>
<p>Sono intervenuti l'assessore Alessia Tortolo, gli storici ed esperti di storia locale <strong>Marco Sicuro</strong>, <strong>Giulia Sattolo</strong> e <strong>Ferruccio Tassin</strong>, Ivaldi Calligaris dell'associazione I Scussons, oltre alla giovane musicista Angela Comuzzi.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/04/OLTRECONFINE-serata-Romans.jpg" alt="Serata Romans d'Isonzo" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/04/OLTRECONFINE-18-Romans-d-Isonzo-assessore-Alessia-Tortolo.jpg" alt="Assessore Alessia Tortolo Romans d'Isonzo" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/04/OLTRECONFINE-18-Romans-relatori-Marco-Sicuro-Giulia-Sattolo-Ferruccio-Tassin-Francesco-Accomando.jpg" alt="Relatori serata Romans - Marco Sicuro, Giulia Sattolo, Ferruccio Tassin, Francesco Accomando" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/04/OLTRECONFINE-18-Romans-d-Isonzo-Ivaldi-Calligaris-associazione-I-Scussons.jpg" alt="Ivaldi Calligaris associazione I Scussons" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/04/OLTRECONFINE-18-Romans-d-Isonzo-Angela-Comuzzi.jpg" alt="Angela Comuzzi" loading="lazy">
<p>Nella galleria il materiale iconografico presentato da Ivaldi Calligaris che ha raccontato la storia di <strong>Ugo Amerigo Toso</strong>: la piazza e la chiesa di Versa (frazione di Romans) prima di Caporetto, il ponte sullo Judrio (l'edificio bianco sulla destra è un ospedale militare, si vede la croce sulla copertura), le opere fortificate lungo il Torre realizzate dal Regio Esercito. Due ufficiali di sanità uno italiano e l'altro inglese – a Romans giunse un'unità di artiglieria inglese e operava un ospedale militare inglese – e Romans dopo Caporetto, con il ritorno dell'esercito austro-ungarico.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/04/OLTRECONFINE-18-Romans-Versa-ponte-sullo-Judrio-edificio-bianco-a-dx-è-un-ospedale-militare.jpg" alt="Versa - ponte sullo Judrio con ospedale militare" loading="lazy">`,

  23: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/03/OLTRECONFINE-serata-Romans.jpg" alt="Serata conclusiva del ciclo serate-forum" loading="lazy">
<p>Un bolscevico armato fino ai denti scende da cavallo e si rivolge ad un prigioniero austroungarico chiedendo: <em>"Pandolo, ma no si cognosino?"</em>. È <strong>Ugo Americo Toso</strong> di Romans d'Isonzo. Arruolato nell'esercito austroungarico e partito per la Galizia nel 1914, era stato fatto prigioniero dai russi abbracciandone poi la causa rivoluzionaria nel 1917.</p>
<p>Quella di Toso è solo una delle storie che il progetto <strong>OLTRECONFINE 1918/2018</strong> ha portato alla luce nel percorso delle serate-forum che, anche quest'anno, hanno costituito il momento fondamentale di raccolta di materiale storico.</p>
<p>Nella terza edizione il progetto sulla memoria della Grande Guerra in Friuli Venezia Giulia si è concentrato sul periodo che va dai fatti di Caporetto, con l'arrivo delle truppe austro-ungariche e tedesche, fino all'armistizio del 4 novembre 1918, fino al nuovo equilibrio post bellico con la stabilizzazione del controllo italiano.</p>
<p>Ricercatori, insegnanti, studiosi, esperti di storia locale e altrettanto importanti raccoglitori di storie si sono alternati nelle serate ospitate dai 17 comuni che partecipano al progetto: Palmanova (capofila), Aiello del Friuli, Bicinicco, Bagnaria Arsa, Campolongo Tapogliano, Chiopris Viscone, Gonars, Ruda, Santa Maria la Longa, San Vito al Torre, Trivignano Udinese, Visco, Castions di Strada, Medea, Romans d'Isonzo, Torviscosa, Villesse. A questi appassionati si sono aggiunte associazioni locali, gruppi musicali e le voci delle comunità che hanno portato nuove testimonianze ereditate e tramandate e ancora vive dopo 100 anni.</p>
<p>Come nelle precedenti edizioni, conclusa la prima fase di OLTRECONFINE si procede con la seconda parte del progetto. Tutti i cittadini interessati a partecipare attivamente costituiscono un laboratorio culturale che, sotto la guida del direttore artistico <strong>Francesco Accomando</strong>, elaborerà i materiali raccolti e preparerà l'evento finale, previsto per la prossima estate.</p>`,

  24: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/03/OLTRECONFINE-18-ospedale-campolongo_-michele-tomeselli.jpg" alt="Ospedale Campolongo - Michele Tomeselli" loading="lazy">
<p>Pubblichiamo un'intervista di approfondimento su <strong>Radio Spazio 103</strong> dedicata al progetto <strong>OLTRECONFINE 1918/2018</strong> per il recupero della memoria di famiglie e comunità del Friuli Venezia Giulia sulla Grande Guerra.</p>
<p>Nell'intervista vengono approfonditi gli obiettivi del progetto, le serate-forum nei 17 comuni coinvolti e il lavoro di raccolta delle testimonianze che costituirà la base per l'evento teatrale finale dell'estate 2018.</p>`,

  25: `<p>Serata densa di contenuti, testimonianze, racconti, ricerche storiche e contributi artistici a <strong>Villesse</strong> in occasione del forum di incontro con la comunità locale nell'ambito del progetto <strong>OLTRECONFINE 1918/2018</strong>.</p>
<p>Dopo il saluto di Flavia Viola assessore alla cultura di Villesse, sono intervenuti come relatori con contributi di ricerca storica <strong>Stefano Perini</strong> e <strong>Ferruccio Tassin</strong>, oltre al <strong>Gruppo storico I Blaudins</strong>. Agnese Portelli (Associazione Villes Art) ha portato la testimonianza sui cittadini di Villesse arruolati nell'esercito e, accompagnata da Guido Gasparini alla chitarra, ha letto alcune poesie. La Sezione Clarinetti della Banda dei Donatori di Sangue di Villesse ha fatto vibrare le note di brani che hanno segnato la storia friulana e delle montagne.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/03/OLTRECONFINE-18-serata-Villesse-Flavia-Viola-assessore-alla-cultura.jpg" alt="Flavia Viola assessore alla cultura di Villesse" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/03/OLTRECONFINE-18-Villesse-Stefano-Perini-relatore.jpg" alt="Stefano Perini relatore" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/03/OLTRECONFINE-18-Villesse-Ferruccio-Tassin-relatore.jpg" alt="Ferruccio Tassin relatore" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/03/OLTRECONFINE-18-Villesse-Gruppo-storico-I-Blaudins.jpg" alt="Gruppo storico I Blaudins" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/03/OLTRECONFINE-18-serata-Villesse-Agnese-Portelli-Associazione-Villes-Art-accompagnata-da-Guido-Gasparini-alla-chitarra.jpg" alt="Agnese Portelli con Guido Gasparini" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/03/OLTRECONFINE-18-serata-Villesse-Francesco-Accomando-lettura.jpg" alt="Francesco Accomando lettura" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/03/OLTRECONFINE-18-serata-Villesse-soldati-di-Villesse-1.jpg" alt="Soldati di Villesse - materiale storico" loading="lazy">`,


  26: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/03/OLTRECONFINE-serata-Villesse.jpg" alt="Serata-forum Torviscosa" loading="lazy">
<p>Ultimo atto nel percorso di ricerca sul territorio di <strong>OLTRECONFINE 1918/2018</strong>. Venerdì 9 marzo alle 20.30 ultima serata-forum al Centro di aggregazione Giovanile di <strong>Torviscosa</strong> per raccogliere testimonianze, documenti, racconti familiari e storie nascoste sulla Grande Guerra in Friuli Venezia Giulia.</p>
<p>Oltre al direttore artistico <strong>Francesco Accomando</strong>, interverranno il sindaco <strong>Roberto Fasan</strong> per un saluto dell'Amministrazione e come relatori <strong>Alessandro De Biasio</strong> accompagnato in lettura da Michele De Caro, per l'Associazione culturale Tormenti, e <strong>Luciano Patat</strong>. Accompagnamenti musicali a cura dell'Associazione Culturale Musica Viva.</p>
<p>Dai fatti di Caporetto dell'autunno 1917, con l'arrivo o il ritorno delle truppe austro-ungariche e tedesche, passando per il rovesciamento del fronte e l'armistizio del 4 novembre 1918, fino all'annessione del 1920: è questo l'arco temporale che la terza edizione di <strong>OLTRECONFINE</strong> percorre nell'anno del centenario della sospirata conclusione di una guerra che si è abbattuta con una violenza brutale sulle aree dei 17 Comuni partecipanti.</p>
<p>«Il progetto intende raccontare storie di uomini e donne, di città e paesi all'epoca della Grande Guerra nell'idea di recuperare brandelli di storia, anche volutamente o inconsapevolmente dimenticati – evidenzia Giampaolo Fioretti, presidente dell'associazione <strong>Cikale Operose</strong> – Per questo cercheremo di coinvolgere, per il terzo anno, associazioni e famiglie nella raccolta di memorie, documenti, diari, fotografie, oggetti legati alla memoria della Grande Guerra».</p>`,

  27: `<p><strong>VISCO – 22 febbraio 2018</strong></p>
<p>Nelle foto della serata emerge la forte partecipazione della comunità locale. Dopo il saluto dell'assessore Mauro Ongaro, sono intervenuti <strong>Giorgio Milocco</strong> e <strong>Giulia Sattolo</strong> come relatori sulla storia locale, Nicoletta Nicola dell'associazione Donne &amp; Armi e il presidente della Consulta Giovani idee. Emozionante il contributo musicale del <strong>Coro Madonna della Neve</strong>.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/03/OLTRECONFINE-18-serata-Visco-1.jpg" alt="Serata Visco 1" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/03/OLTRECONFINE-18-serata-Visco-Giorgio-Milocco-e-Giulia-Sattolo-relatori.jpg" alt="Giorgio Milocco e Giulia Sattolo relatori" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/03/OLTRECONFINE-18-serata-Visco-Coro-Madonna-della-Neve.jpg" alt="Coro Madonna della Neve" loading="lazy">
<p><strong>BAGNARIA ARSA – 23 febbraio 2018</strong></p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/03/OLTRECONFINE-18-serata-Visco-2.jpg" alt="Serata Bagnaria Arsa" loading="lazy">`,


  28: `<p><strong>Aiello – 30 gennaio 2017</strong></p>
<p>Nella serata-forum ad <strong>Aiello del Friuli</strong> sono intervenuti <strong>Andrea Bellavite</strong> sindaco di Aiello, gli esperti di storia locale <strong>Stefano Perini</strong> e <strong>Ferruccio Tassin</strong>, il direttore artistico <strong>Francesco Accomando</strong> e <strong>Bruno Chiaranti</strong>, attore di Oltreconfine, che ha portato alcuni brani di una sua storia ispirata dalle vicende del nonno materno e dello zio che si sono trovati su fronti opposti.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/03/OLTRECONFINE-Andrea-Bellavite-sindaco-di-Aiello.jpg" alt="Andrea Bellavite sindaco di Aiello" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/03/Stefano-Perini-storico.jpg" alt="Stefano Perini storico" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/03/Ferruccio-Tassin-storico.jpg" alt="Ferruccio Tassin storico" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/03/OLTRECONFINE-Francesco-Accomando.jpg" alt="Francesco Accomando" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/03/Bruno-Chiaranti-attore-di-Oltreconfine.jpg" alt="Bruno Chiaranti attore di Oltreconfine" loading="lazy">
<p>Il prof. Ferruccio Tassin è intervenuto sui <strong>preti della zona di Aiello prima internati e poi inviati al confino</strong> in diverse regioni d'Italia. L'intervento era corredato dai seguenti documenti storici:</p>
<ul>
  <li>Cartolina di don Stacul (di Aiello) al parroco Decano</li>
  <li>Lettera di don Antonio Carrara</li>
  <li>Resoconto delle somme corrisposte ai preti al confino</li>
  <li>Composizione di Maria Nardin di Aiello</li>
</ul>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/03/cartolina-prete-confino.jpg" alt="Cartolina prete al confino" loading="lazy">`,

  29: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2017/12/OLTRECONFINE-ospedale-militare-Romans-dIsonzo-1.jpg" alt="Arrivo di feriti ad un ospedale di Romans d'Isonzo" loading="lazy">
<p><em>Arrivo di feriti ad un ospedale di Romans d'Isonzo</em></p>
<p>Due appuntamenti ravvicinati nel percorso di ricerca sul territorio di <strong>OLTRECONFINE 1918/2018</strong>. Giovedì 1 e venerdì 2 marzo nuove tappe a <strong>Romans d'Isonzo</strong> e a <strong>Trivignano Udinese</strong> per raccogliere testimonianze, documenti, racconti familiari e storie nascoste sulla Grande Guerra in Friuli Venezia Giulia.</p>
<p>Le serate-forum sulla memoria con associazioni, gruppi organizzati, scuole e cittadini (dalle ore 20.30) saranno ospitate rispettivamente alla <strong>Casa Candussi Pasiani</strong> e al <strong>Museo Comunale di Clauiano</strong>.</p>
<p>Oltre al direttore artistico <strong>Francesco Accomando</strong>, interverranno come relatori sui contenuti storici <strong>Giulia Sattolo</strong> e <strong>Ferruccio Tassin</strong>, mentre contributi di testimonianza verranno dall'Associazione Scussons – Ivaldi Calligaris con lettura e immagini e ci saranno interventi musicali dell'associazione Il Flauto Magico.</p>
<p>Dai fatti di Caporetto dell'autunno 1917, con l'arrivo o il ritorno delle truppe austro-ungariche e tedesche, passando per il rovesciamento del fronte e l'armistizio del 4 novembre 1918, fino all'annessione del 1920: è questo l'arco temporale che la terza edizione di <strong>OLTRECONFINE</strong> percorre nell'anno del centenario della conclusione della guerra.</p>
<p>Il calendario delle serate-forum di OLTRECONFINE 1918/2018 si chiudeva a Torviscosa il venerdì 9 marzo – Centro aggregazione Giovanile.</p>`,


  30: `<p>Serata densa di approfondimenti storici, testimonianze, racconti a <strong>Medea</strong> in occasione del forum di <strong>OLTRECONFINE 1918/2018</strong>.</p>
<p>Dopo i saluti dell'assessore <strong>Raffaella Cantarutti</strong>, sono intervenuti <strong>Giorgio Milocco</strong> e <strong>Gianluigi Martinis</strong>, <strong>Franco Stacul</strong> presidente dell'associazione Amici della Croce Nera Austriaca e <strong>Renato Cisilin</strong> dell'ANA, oltre al direttore artistico <strong>Francesco Accomando</strong>.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-18-serata-forum-Medea-1.jpg" alt="Serata-forum Medea" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-serata-Medea.jpg" alt="Serata Medea pubblico" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-18-forum-Medea-Milocco.jpg" alt="Giorgio Milocco relatore" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-18-forum-Medea-Cisilin.jpg" alt="Renato Cisilin ANA" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-18-forum-Medea-Stacul.jpg" alt="Franco Stacul Croce Nera Austriaca" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-18-forum-Medea-Martinis.jpg" alt="Gianluigi Martinis" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-serata-Medea-F-Accomando-1.jpg" alt="Francesco Accomando" loading="lazy">
<p>Dalla serata, tra i contributi più significativi: Gianluigi Martinis ha raccontato del nonno soldato austro-ungarico, prigioniero dei russi e poi ritornato a casa; Renato Cisilin dell'ANA ha presentato l'attività dell'associazione per la memoria dei caduti e per la pace; Franco Stacul ha illustrato l'attività degli Amici della Croce Nera Austriaca per la memoria dei caduti austro-ungarici friulani. La giovane chitarrista Marta Turan ha eseguito un brano dedicato alla memoria.</p>`,

  31: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-2018-serata-forum-Villesse.jpg" alt="Serata-forum S. Maria la Longa" loading="lazy">
<p><strong>OLTRECONFINE 1918/2018</strong> si avvia alla conclusione del percorso di ricerca sul territorio con una nuova tappa a <strong>Santa Maria la Longa</strong> per raccogliere testimonianze, documenti, racconti familiari e storie nascoste sulla Grande Guerra in Friuli Venezia Giulia. Martedì 27 febbraio alle 20.30 nella sala della Biblioteca don Luigi De Biasio associazioni, gruppi organizzati, scuole e cittadini sono invitati ad un dialogo aperto per il recupero della memoria.</p>
<p>Oltre al direttore artistico <strong>Francesco Accomando</strong> e all'assessore <strong>Donatella Urban</strong>, interverranno come relatori sui contenuti storici <strong>Giulia Sattolo</strong> e <strong>Antonino di Colloredo Mels</strong>, inoltre <strong>Paolo Bonini</strong> dell'associazione Lapis e <strong>Carlo Del Mestre</strong>. Saranno presentate letture a cura di Giovanna Bortolussi e Martino Buchini della Commissione Biblioteca e brani musicali eseguiti dal <strong>Coro Punto&amp;acapo</strong> dell'Associazione Laboratorio musicale Arsound.</p>
<p>Il calendario delle serate seguenti prevedeva: Romans d'Isonzo (giovedì 1 marzo, Casa Candussi Pasiani), Trivignano Udinese (venerdì 2 marzo, Museo Comunale di Clauiano), Torviscosa (venerdì 9 marzo, Centro aggregazione Giovanile).</p>`,


  32: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-serata-forum.jpg" alt="Serata-forum Bagnaria Arsa" loading="lazy">
<p>Il progetto <strong>OLTRECONFINE 1918/2018</strong> fa una nuova tappa a <strong>Bagnaria Arsa</strong> per raccogliere testimonianze, documenti, racconti familiari e storie nascoste sulla Grande Guerra in Friuli Venezia Giulia. Venerdì 23 febbraio alle 20.30 nella <strong>Baita Alpini di Sevegliano</strong> associazioni, gruppi organizzati, scuole e cittadini sono invitati ad un dialogo aperto per il recupero della memoria.</p>
<p>Oltre al direttore artistico <strong>Francesco Accomando</strong>, interverranno come relatori storici <strong>Cristiano Tiussi</strong>, <strong>Enrico Pin</strong> e <strong>Alessandro De Biasio</strong>. Sono previste inoltre una testimonianza di <strong>Alessandro Sandra</strong>, una lettura di <strong>Renato Sclauzero</strong> e contributi musicali del duo flauto traverso-chitarra composto da <strong>Noela Ontani</strong> e <strong>Giovanni Grisan</strong>.</p>
<p>Il calendario delle serate successive prevedeva: Santa Maria la Longa (martedì 27 febbraio, Biblioteca don Luigi De Biasio), Romans d'Isonzo (giovedì 1 marzo, Casa Candussi Pasiani), Trivignano Udinese (venerdì 2 marzo, Museo Comunale di Clauiano), Torviscosa (venerdì 9 marzo, Centro aggregazione Giovanile).</p>`,

  33: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-Campolongo-Tapogliano-Stefano-Perini-e-Giulia-Sattolo.jpg" alt="Stefano Perini e Giulia Sattolo relatori" loading="lazy">
<p>Il progetto <strong>OLTRECONFINE 1918/2018</strong> fa una nuova tappa a <strong>Visco</strong> per raccogliere testimonianze, documenti, racconti familiari e storie nascoste sulla Grande Guerra in Friuli Venezia Giulia. Giovedì 22 febbraio alle 20.30 negli spazi dell'<strong>ex Dogana Austriaca</strong> associazioni, gruppi organizzati, scuole e cittadini sono invitati ad un dialogo aperto per il recupero della memoria.</p>
<p>Oltre al direttore artistico <strong>Francesco Accomando</strong>, interverranno come relatori gli storici <strong>Giorgio Milocco</strong> e <strong>Giulia Sattolo</strong>. Ci saranno inoltre contributi dell'Associazione culturale Donne &amp; Armi e della Consulta Giovani Idee. Il <strong>Coro Parrocchiale Madonna della Neve</strong> interpreterà alcuni brani musicali nel corso della serata.</p>
<p>Il calendario delle serate successive prevedeva: Bagnaria Arsa (venerdì 23 febbraio, Baita Alpini di Sevegliano), Santa Maria la Longa (martedì 27 febbraio, Biblioteca don Luigi De Biasio), Romans d'Isonzo (giovedì 1 marzo, Casa Candussi Pasiani), Trivignano Udinese (venerdì 2 marzo, Museo Comunale di Clauiano), Torviscosa (venerdì 9 marzo, Centro aggregazione Giovanile).</p>`,


  34: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-Campolongo-Tapogliano.jpg" alt="Serata-forum Villesse" loading="lazy">
<p>Il progetto <strong>OLTRECONFINE 1918/2018</strong> approda a <strong>Villesse</strong> per raccogliere testimonianze, documenti, racconti familiari e storie nascoste sulla Grande Guerra in Friuli Venezia Giulia. Martedì 20 febbraio alle 20.30 nella sala consiliare di <strong>Palazzo Ghersiach</strong> associazioni, gruppi organizzati, scuole e cittadini sono invitati ad un dialogo aperto per il recupero della memoria.</p>
<p>Oltre al direttore artistico <strong>Francesco Accomando</strong>, interverranno come relatori gli storici <strong>Stefano Perini</strong> e <strong>Ferruccio Tassin</strong>. Ci saranno inoltre contributi dell'associazione <em>Villes Art</em> con brani poetici e accompagnamento musicale di <em>Guido Gasparini</em> alla chitarra, del gruppo clarinetti della <em>Banda dei Donatori di Sangue</em>, e testimonianze a cura di <strong>Agnese Portelli</strong>.</p>`,

  35: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-serata-Medea-F-Accomando.jpg" alt="Francesco Accomando serata Gonars" loading="lazy">
<p>Dopo Palmanova, il progetto <strong>OLTRECONFINE 1918/2018</strong> fa tappa a <strong>Gonars</strong> per raccogliere testimonianze, documenti, racconti familiari e storie sulla Grande Guerra in Friuli Venezia Giulia. Venerdì 16 febbraio alle 20.30 nella sala del <strong>Centro civico di Fauglis</strong> l'Amministrazione e gli organizzatori invitano associazioni, gruppi organizzati, scuole e cittadini ad un dialogo aperto per il recupero della memoria.</p>
<p>Oltre al direttore artistico <strong>Francesco Accomando</strong>, interverranno come relatori gli storici <strong>Marco Sicuro</strong> e <strong>Edoardo Colombaro</strong> dell'Associazione Stradalta. Ci saranno inoltre contributi musicali del <em>Coro Sine Tempore</em> e letture a cura del gruppo <em>Officina Teatrale</em>.</p>
<p>Il calendario delle serate successive prevedeva: Villesse (martedì 20 febbraio, Palazzo Ghersiach), Visco (giovedì 22 febbraio, Ex-Dogana Austriaca), Bagnaria Arsa (venerdì 23 febbraio, Baita Alpini di Sevegliano), Santa Maria la Longa (martedì 27 febbraio, Biblioteca don Luigi De Biasio), Romans d'Isonzo (giovedì 1 marzo, Casa Candussi Pasiani), Trivignano Udinese (venerdì 2 marzo, Museo Comunale di Clauiano), Torviscosa (venerdì 9 marzo).</p>`,

  36: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-Campolongo-Tapogliano.jpg" alt="Serata-forum Palmanova" loading="lazy">
<p>Una nuova serata-forum nel progetto <strong>OLTRECONFINE 1918/2018</strong> per raccogliere testimonianze, documenti, racconti familiari, storie sulla Grande Guerra in Friuli Venezia Giulia. Giovedì 15 febbraio alle 20.30 nel <strong>Salone d'onore del Municipio di Palmanova</strong> un nuovo incontro con associazioni, scuole e cittadini.</p>
<p>Oltre al direttore artistico <strong>Francesco Accomando</strong> e al vicesindaco <strong>Adriana Danielis</strong>, interverranno come relatori gli storici <strong>Alberto Prelli</strong> e <strong>Giulia Sattolo</strong>, l'Accademia Nuova Esperienza Teatrale, testimonianze dall'associazione Libermente (a cura di Daniela Galeazzi, Clara Maggiore e Renata Sasso), testimonianze sulla frazione di Ialmicco a cura di Enzo Liberale. Partecipa, per l'Accademia Musicale Città di Palmanova, la violinista <strong>Mariko Masuda</strong>.</p>
<p>«Siamo giunti alla fase del confronto diretto con il territorio per recuperare quanto la storia testimoniale ha ancora da raccontarci – commenta la vicesindaco <strong>Adriana Danielis</strong> – Questo incontro permetterà la costruzione di un quadro più generale sui fatti e vissuti dopo Caporetto in queste aree della nostra regione. Palmanova e tutta la Regione fino al nuovo fronte sul Piave furono occupate dalle forze austro-germaniche con pesanti ripercussioni sulla popolazione civile. Profuganza, prigionia e miseria costituivano parole d'ordine nella profonda lacerazione del tessuto sociale di quel periodo».</p>`,


  37: `<p>Gli eventi accaduti prima e dopo la disfatta di Caporetto, il ritorno e le persecuzioni sulle popolazioni italiane, sono stati il perno degli approfondimenti storici nella serata-evento di <strong>OLTRECONFINE 1918/2018</strong> a <strong>Campolongo Tapogliano</strong>.</p>
<p>Nel corso della serata sono intervenuti l'assessore locale <strong>Antonio Rosolini</strong>, il direttore artistico <strong>Francesco Accomando</strong>, <strong>Marco Sicuro</strong> ricercatore dello staff di Oltreconfine per la raccolta materiali storici, oltre agli storici <strong>Stefano Perini</strong> e <strong>Giulia Sattolo</strong>.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/intervento-assessore-Antonio-Rosolini-di-Campolongo-Tapogliano-OLTRECONFINE.jpg" alt="Assessore Antonio Rosolini" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/Marco-Sicuro-ricercatore-staff-OLTRECONFINE-per-raccolta-materiali-storici.jpg" alt="Marco Sicuro ricercatore" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-Campolongo-Tapogliano-Francesco-Accomando.jpg" alt="Francesco Accomando Campolongo" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-Campolongo-Tapogliano-Stefano-Perini-e-Giulia-Sattolo.jpg" alt="Stefano Perini e Giulia Sattolo" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-Campolongo-Tapogliano.jpg" alt="Serata Campolongo Tapogliano" loading="lazy">
<p>Nella serata Stefano Perini ha parlato di Campolongo dalla rotta di Caporetto al ritorno degli italiani; Giulia Sattolo ha trattato le violenze sulle popolazioni italiane dopo Caporetto; Francesco Accomando ha interpretato una lettura recitata da <em>"Ritorno a casa"</em> di E.M. Remarque.</p>`,

  38: `<p>Serata di memorie e testimonianze intense a <strong>Chiopris Viscone</strong> nel progetto <strong>OLTRECONFINE 1918/2018</strong>.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-Chiopris-Viscone-Francesco-Accomando.jpg" alt="Francesco Accomando a Chiopris Viscone" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-Chiopris-Viscone-sacerdote.jpg" alt="Don Massimiliano De Pelca, sacerdote internato" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-Chiopris-Viscone-libro.jpg" alt="Libro di Maria Masau Dan sulle memorie familiari" loading="lazy">
<p>Nella serata sono stati presentati la foto del direttore artistico <strong>Francesco Accomando</strong>, quella del sacerdote <strong>don Massimiliano De Pelca</strong>, uno dei tanti preti internati dopo il 1915, e la copertina del libro che <strong>Maria Masau Dan</strong>, ex direttrice del Museo Rivoltella di Trieste, ha dedicato alle memorie della sua famiglia travolta dalle vicende belliche. La testimonianza di Maria Masau Dan sull'avvento della Grande Guerra è stata poi raccolta in un video dalla redazione del progetto.</p>`,

  39: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/Stefano-Perini-storico.jpg" alt="Stefano Perini storico" loading="lazy">
<p>Tre serate-forum consecutive nel progetto <strong>OLTRECONFINE 1918/2018</strong> per raccogliere testimonianze, documenti, racconti familiari, storie sulla Grande Guerra in Friuli Venezia Giulia. Gli incontri con associazioni, scuole e cittadini sono fissati per lunedì 5 febbraio nel Municipio di <strong>Ruda</strong>, martedì 6 febbraio nel Municipio di <strong>Campolongo Tapogliano</strong> e mercoledì 7 febbraio nella sala parrocchiale don Ulian a <strong>Medea</strong>.</p>
<p>Oltre al direttore artistico <strong>Francesco Accomando</strong>: a Ruda interverranno gli storici <strong>Giorgio Milocco</strong> e <strong>Adriana Miceu</strong>; a Campolongo Tapogliano <strong>Stefano Perini</strong> e <strong>Giulia Sattolo</strong>; a Medea <strong>Giorgio Milocco</strong> e <strong>Franco Stacul</strong>.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-serata-San-Vito-al-Torre-5.jpg" alt="Serata San Vito al Torre" loading="lazy">
<p>Il calendario delle serate successive prevedeva: Palmanova (giovedì 15 febbraio, Municipio), Gonars (venerdì 16 febbraio, Centro civico di Fauglis), Chiopris Viscone, San Vito al Torre, Bicinicco, Aiello del Friuli, San Vito al Torre, Castions di Strada, Villesse, Visco, Bagnaria Arsa, Santa Maria la Longa, Romans d'Isonzo, Trivignano Udinese, Torviscosa.</p>`,


  40: `<p>Ecco alcune foto della serata-forum a <strong>San Vito al Torre</strong> (ph Gianni Russo)</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-serata-San-Vito-al-Torre-2.jpg" alt="Serata San Vito al Torre 1" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-serata-San-Vito-al-Torre-3.jpg" alt="Serata San Vito al Torre 2" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-serata-San-Vito-al-Torre-4.jpg" alt="Serata San Vito al Torre 3" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-serata-San-Vito-al-Torre-5.jpg" alt="Serata San Vito al Torre 4" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-serata-San-Vito-al-Torre-6.jpg" alt="Serata San Vito al Torre 5" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-serata-San-Vito-al-Torre-7.jpg" alt="Serata San Vito al Torre 6" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-serata-San-Vito-al-Torre-8.jpg" alt="Serata San Vito al Torre 7" loading="lazy">
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-serata-San-Vito-al-Torre.jpg" alt="Serata San Vito al Torre" loading="lazy">
<p>Nella serata sono stati presentati: l'intervento di <strong>Gianluca Comar</strong> sul rientro dei prigionieri e sulla rotta di Caporetto; l'intervento di <strong>Giorgio Milocco</strong> sul rientro dei prigionieri dalla Galizia; il <strong>Coro parrocchiale San Casciano</strong> che ha cantato <em>"Daur San Pieri"</em>.</p>`,

  41: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/02/OLTRECONFINE-aiello.jpg" alt="Serata Bicinicco" loading="lazy">
<p>Quinta serata-forum nell'ambito del progetto <strong>OLTRECONFINE 1918/2018</strong>. Venerdì 2 febbraio alle 20.30 nella sala polifunzionale <strong>don Lino Andreoli</strong> a <strong>Bicinicco</strong> è fissato l'incontro con associazioni, scuole e cittadini per la ricerca e valorizzazione della memoria della Grande Guerra in Friuli Venezia Giulia.</p>
<p>Il calendario delle serate successive prevedeva: Ruda (lunedì 5 febbraio, Municipio), Campolongo Tapogliano (martedì 6 febbraio, Palazzo Municipale), Medea (mercoledì 7 febbraio, Sala Parrocchiale don Ulian), Palmanova (giovedì 15 febbraio, Municipio), Gonars (venerdì 16 febbraio, Centro Civico di Fauglis), Villesse (martedì 20 febbraio, Palazzo Ghersiach), Visco (giovedì 22 febbraio, Ex-Dogana Austriaca), Bagnaria Arsa (venerdì 23 febbraio, Baita Alpini di Sevegliano), Santa Maria la Longa (martedì 27 febbraio, Biblioteca don Luigi De Biasio), Romans d'Isonzo (giovedì 1 marzo, Casa Candussi Pasiani), Trivignano Udinese (venerdì 2 marzo, Museo Comunale di Clauiano), Torviscosa.</p>`,


  42: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/01/OLTRECONFINE-san-vito-forum.jpg" alt="Serata-forum Aiello del Friuli" loading="lazy">
<p>Quarta serata-forum nell'ambito del progetto <strong>OLTRECONFINE 1918/2018</strong>. Martedì 30 gennaio alle 20.30 nella sala civica ad <strong>Aiello del Friuli</strong> è stato organizzato l'incontro con associazioni, scuole e cittadini per la ricerca e valorizzazione della memoria della Grande Guerra in Friuli Venezia Giulia.</p>
<p>Dai fatti di Caporetto dell'autunno 1917, con l'arrivo o il ritorno delle truppe austro-ungariche e tedesche, passando per il rovesciamento del fronte e l'armistizio del 4 novembre 1918, fino all'annessione del 1920: è questo l'arco temporale che la terza edizione di <strong>OLTRECONFINE</strong> percorre nell'anno del centenario della conclusione della guerra.</p>
<p>Il calendario delle serate successive prevedeva: Bicinicco (venerdì 2 febbraio, Sala Polifunzionale don Lino Andreoli), Ruda (lunedì 5 febbraio, Municipio), Campolongo Tapogliano (martedì 6 febbraio, Palazzo Municipale), Medea (mercoledì 7 febbraio, Sala Parrocchiale don Ulian), Palmanova (giovedì 15 febbraio, Municipio), Gonars (venerdì 16 febbraio, Centro Civico di Fauglis).</p>`,

  43: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2017/11/OLTRECONFINE-SAN-VITO-AL-TORRE-spettacolo2.jpg" alt="San Vito al Torre spettacolo 2017" loading="lazy">
<p>Dopo Castions di Strada e Chiopris Viscone, il progetto <strong>OLTRECONFINE 1918/2018</strong> fa tappa a <strong>San Vito al Torre</strong>. Giovedì 25 gennaio alle 20.30 la sala parrocchiale ospita la terza delle serate-forum con associazioni, scuole e cittadini per la ricerca e valorizzazione della memoria della Grande Guerra in Friuli Venezia Giulia.</p>
<p>Il progetto triennale si concentra sul periodo che va dai fatti di Caporetto dell'autunno 1917, con l'arrivo o il ritorno delle truppe austro-ungariche e tedesche, passando per il rovesciamento del fronte e l'armistizio del 4 novembre 1918, fino all'annessione del 1920.</p>`,

