// ══════════════════════════════════════════════════════════════════
//  CONTENUTI COMPLETI — testo integrale di tutti gli articoli
//  Copiato dal sito originale oltreconfine-ww1.eu
// ══════════════════════════════════════════════════════════════════
const CONTENT = {

  0: `<p>«Qui finisce la nostra "storia di un confine". Ma questo momento è solo un fatto transitorio, un passaggio, attraverso una soglia che porterà a nuovi confini». È racchiuso in queste parole scritte dal direttore artistico <strong>Francesco Accomando</strong> il senso del progetto <strong>OLTRECONFINE</strong>, un progetto culturale pluriennale sulla Grande Guerra nato dall'esigenza di creare, in un'area che all'epoca era attraversata da un confine, un immaginario storico, comune e condiviso, di alcuni avvenimenti significativi, nella pluralità dei punti di vista e nel superamento di alcune distorsioni, mistificazioni e manomissioni intercorse negli anni successivi. Il progetto ha preso avvio nel 2015 su iniziativa e coordinamento del Comune di Palmanova, capofila dell'iniziativa, nell'ambito delle celebrazioni per i cento anni dalla Prima Guerra mondiale e si è concluso nel 2019-2020 con la fase di raccolta documentale sull'esperienza maturata.</p>
<p>OLTRECONFINE è stato un progetto "dal basso", articolato in più fasi per ogni annualità: la prima prevedeva incontri con la cittadinanza in serate-forum animate da cori, bande e gruppi culturali locali e aperte all'intervento di esperti storici e semplici cittadini che hanno portato memorie, storie e materiali anche inediti; nella seconda, il direttore artistico ha rielaborato tutto questo in forma drammaturgica attraverso laboratori teatrali cui hanno partecipato i cittadini stessi, molti dei quali alla loro primissima esperienza teatrale; infine il tutto è stato "restituito" da questi stessi cittadini in forma di spettacolo, replicato in ogni Comune partecipante al progetto. I Comuni coinvolti, e sostenitori con proprie risorse del progetto, sono stati 12 in avvio e dal secondo anno 17, evidenziando l'ampio coinvolgimento di un territorio legato alle drammatiche vicende del "confine" e del suo essere storicamente "oltre".</p>
<p>Ora quel percorso è <strong>raccolto in una pubblicazione in tre volumi</strong> – ciascuno dedicato ad uno degli anni di guerra – che si può acquistare in formato cartaceo contattando direttamente l'associazione Cikale Operose (cikaleoperose@gmail.com) oppure online su Amazon in versione cartacea o in ebook.</p>
<p>«Il volume OLTRECONFINE intende raccontare storie di uomini e donne, la gente comune di paese all'epoca della Grande Guerra – evidenziano <strong>Francesco Accomando, Giampaolo Fioretti</strong> e <strong>Gianni Russo</strong> dello staff di direzione – nell'idea di recuperare brandelli di storia, anche volutamente o inconsapevolmente dimenticati, guardando anche al nostro presente, nella consapevolezza che la memoria storica può aiutare a comprendere altri conflitti e altri confini che oggi si presentano sul nostro orizzonte; saper guardare con gli occhi della storia a quei fenomeni epocali, a quelle tensioni politiche e culturali, locali, nazionali e internazionali, che si dovranno superare, per arrivare a ricucire strappi e a rafforzare una cultura della pace e della convivenza sulla strada della costruzione di una vera Europa dei popoli e dei cittadini».</p>
<p>«La consapevolezza della Storia, originatasi sui drammi delle popolazioni, risulta essere l'unico strumento in grado di incidere sul presente e di proiettarne le attese sul futuro. I destinatari principali del progetto sono le nuove generazioni che, attraverso la scuola, saranno i depositari della Memoria di questi luoghi – rimarcano il sindaco di Palmanova <strong>Francesco Martines</strong> e il vicesindaco <strong>Adriana Danielis</strong> – In questo percorso è apparso indispensabile il coinvolgimento del territorio, delle sue risorse umane e materiali e dei luoghi della memoria, dove poter rielaborare il dramma collettivo per ritrovare i valori della solidarietà e della cooperazione. Un dovuto ringraziamento va a tutte le Amministrazioni comunali che hanno creduto in questo progetto, articolato e complesso, ma originale e unico nel suo genere e a tutte le figure che a vario titolo hanno donato il loro tempo, competenze e passione».</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/09/OLTRECONFINE-2018-passeggiata-teatrale-Ara-Pacis-Medea-2.jpg" alt="Passeggiata teatrale Ara Pacis Medea 2018" loading="lazy">
<p>OLTRECONFINE è un progetto partecipato che ha riunito i cittadini e le associazioni di 17 comuni del FVG per quattro annualità: Palmanova (capofila), Aiello del Friuli, Bagnaria Arsa, Bicinicco, Campolongo Tapogliano, Castions di Strada, Chiopris Viscone, Gonars, Medea, Romans D'Isonzo, Ruda, San Vito al Torre, Santa Maria La Longa, Torviscosa, Trivignano Udinese, Villesse, Visco. Tutti territori che, nel 1915, si trovarono "presi in mezzo" dalla guerra, essendo suddivisi tra Impero Austro-Ungarico e Regno d'Italia.</p>`,

  1: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/09/OLTRECONFINE-2018-passeggiata-teatrale-Ara-Pacis-Medea-1.jpg" alt="Passeggiata teatrale Ara Pacis Medea" loading="lazy">
<p>«Qui finisce la nostra "storia di un confine". Ma questo momento è solo un fatto transitorio, un passaggio, attraverso una soglia che porterà a nuovi confini. Abbiamo raccontato una parte importante della nostra storia, come abbiamo saputo, l'abbiamo raccontata come abbiamo potuto, nel tempo fugace di una rappresentazione. Ora, per favore, non lasciateci qui, il mare è calmo, ma ci attendono nuove sfide e nuove tempeste. Non lasciateci annegare nel buio e nell'oblio. Portateci con voi, nel vostro cuore e nella vostra immaginazione. E il ricordo di noi e di quello che vi abbiamo raccontato, donne e uomini che hanno vissuto, sia memoria, che vive nel presente, e così diviene, presenza».</p>
<p>Si è conclusa con queste battute davvero toccanti la straordinaria serata finale – lo scorso 29 agosto all'<strong>Ara Pacis Mundi di Medea</strong> – del progetto <strong>OLTRECONFINE</strong> sulla Grande Guerra. Oltre 150 spettatori hanno accompagnato gli attori nell'ultima passeggiata teatrale dell'edizione 2018, una processione laica intitolata "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" che ha portato un vero e toccante coinvolgimento delle comunità a partire dalle strade e dalle piazze.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/09/OLTRECONFINE-2018-gruppo-attori.jpg" alt="Gruppo attori Oltreconfine 2018" loading="lazy">
<p>Per quasi due mesi l'evento teatrale di OLTRECONFINE – un progetto diretto da <strong>Francesco Accomando</strong> con il coordinamento di <strong>Giampaolo Fioretti</strong>, <strong>Giovanni Russo</strong> e l'organizzazione di <strong>Cikale Operose</strong> – <strong>ha coinvolto più di mille persone</strong> all'interno delle comunità dei paesi toccati dalla "passeggiata". Ad accompagnare la passeggiata tra strade di campagna, vicoli, viali alberati, cimiteri fino all'ultima salita sul colle di Medea, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Franco D'Ambrosio, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Sandra Mansutti, Alessio Michelin, Romeo Mischis, Andrea Nicola, Massimiliana Olivo, Renato Sclauzero, Bruno Tomasin, Francesco Ursella e Fabio Vidoz.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/08/20180829-001-ara-pacis.jpg" alt="Ara Pacis Medea 29 agosto 2018" loading="lazy">
<p>Con l'ultimo evento a Medea si è concluso il percorso teatrale del progetto OLTRECONFINE sulla Grande Guerra, nato dall'esigenza di creare, in un'area che era attraversata da un confine, un immaginario storico comune e condiviso rispetto ad alcuni avvenimenti significativi nella pluralità dei punti di vista e nel superamento di alcune distorsioni, mistificazioni e manomissioni intercorse negli anni successivi.</p>
<p>OLTRECONFINE è un progetto partecipato che ha riunito i cittadini e le associazioni di 17 comuni del FVG: Palmanova (capofila), Aiello del Friuli, Bagnaria Arsa, Bicinicco, Campolongo Tapogliano, Castions di Strada, Chiopris Viscone, Gonars, Medea, Romans D'Isonzo, Ruda, San Vito al Torre, Santa Maria La Longa, Torviscosa, Trivignano Udinese, Villesse, Visco. Tutti territori che, nel 1915, si trovarono "presi in mezzo" dalla guerra, essendo a ridosso o sul confine tra l'Impero Austro-Ungarico e il Regno d'Italia.</p>
<p>«Un percorso lungo tre anni che ha saputo coinvolgere molte persone legate da un passato comune, vissuto nei territori di confine coinvolti nel primo grande conflitto mondiale – sottolinea la vicesindaco di Palmanova <strong>Adriana Danielis</strong> – Il lavoro di molti appassionati e studiosi di storia è riuscito a far emergere fatti e memorie spesso sepolte, che ora possono diventare finalmente patrimonio comune. Palmanova è orgogliosa di essere stata capofila di un progetto culturale innovativo, e sicuramente riuscito, volto a recuperare e salvaguardare una parte della storia di questi luoghi e di queste persone. Un progetto sapientemente trasferito in drammaturgia collettiva nel quale moltissimi volontari hanno dato il proprio grande contributo. Voglio rivolgere ancora il più sentito ringraziamento e plauso al lavoro realizzato in questi anni».</p>
<p>La chiusura del progetto vedrà anche l'edizione di una pubblicazione che andrà a raccogliere documenti e memorie.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/09/OLTRECONFINE-2018-passeggiata-teatrale-Ara-Pacis-Medea-2.jpg" alt="Passeggiata teatrale Ara Pacis Medea" loading="lazy">
<p>«Qui ora finisce Oltreconfine – ha dichiarato al termine della salita a Medea <strong>Francesco Accomando</strong> – Davanti a questo tempio noi ricordiamo i caduti della Grande Guerra, militari e civili, perché anche i civili l'hanno combattuta. Ricordiamo i caduti ma ricordiamo anche quelli che non sono caduti, i sopravvissuti nonostante le mutilazioni del corpo, della mente, del cuore. Noi siamo i loro discendenti. Ma questa serata la dedichiamo anche a quelli che vivono senza memoria del passato, perché sono meno fortunati di noi che sentiamo invece la responsabilità di portare avanti la storia dei nostri cari defunti. Oltre ogni distinzione di nazionalità, genere, ceto o cultura quello della memoria è un dovere per i vivi, un diritto per i morti».</p>`,

  2: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/08/20180829-001-ara-pacis.jpg" alt="Ara Pacis Medea passeggiata teatrale" loading="lazy">
<p>Un evento straordinario, carico di emozione e poesia, conclude il percorso triennale del progetto <strong>OLTRECONFINE</strong> che ha coinvolto 17 Comuni del Friuli Venezia Giulia con capofila Palmanova.</p>
<p>La "passeggiata teatrale" di <strong>OLTRECONFINE 1918/2018</strong> salirà fino all'Ara Pacis di MEDEA mercoledì 29 agosto con una sorta di processione laica dedicata alla memoria della prima guerra mondiale. Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 20.15 dal colle di Medea e si svilupperà in salita verso il monumento avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>L'evento teatrale si presenta come una processione laica, sulla quale il direttore artistico <strong>Francesco Accomando</strong>, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti nella costruzione di una restituzione drammaturgica delle memorie raccolte.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/08/OLTRECONFINE-2018-passeggiata-teatrale-col.jpg" alt="Oltreconfine 2018 passeggiata teatrale" loading="lazy">
<p>"<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" ha portato un vero e toccante coinvolgimento delle comunità a partire dalle strade e dalle piazze. L'intera comunità dei paesi toccati dalla "processione" laica è stata invitata a partecipare, per vivere l'emozione di una memoria lontana cent'anni eppure ancora viva nelle famiglie che hanno sofferto il dramma su un confine che è divenuto un fronte cruciale per le sorti della Prima Guerra Mondiale.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita (l'organizzazione consiglia abbigliamento e scarpe comodi). La passeggiata teatrale si svolge all'aperto, dunque in caso di maltempo l'evento dovrà essere rinviato.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/08/OC-2018.jpg" alt="Locandina OC 2018" loading="lazy">
<p>Nei mesi di lavoro si sono incrociate le relazioni degli storici locali e le memorie di singoli cittadini che hanno dato vita una struttura che unisce narrazione e azioni sceniche. Le storie narrate seguiranno l'idea di uno sguardo dal basso, popolare, di gente semplice che viveva a ridosso del confine, rielaborato attraverso i linguaggi della contemporaneità, fatti di parole, musica, immagini evocate e gestualità scenica.</p>
<p><strong>OLTRECONFINE</strong> è un progetto partecipato che ha riunito i cittadini e le associazioni di 17 comuni del FVG: Palmanova (capofila), Aiello del Friuli, Bagnaria Arsa, Bicinicco, Campolongo Tapogliano, Castions di Strada, Chiopris Viscone, Gonars, Medea, Romans D'Isonzo, Ruda, San Vito al Torre, Santa Maria La Longa, Torviscosa, Trivignano Udinese, Villesse, Visco. Tutti territori che, nel 1915, si trovarono "presi in mezzo" dalla guerra, essendo a ridosso o sul confine tra l'Impero Austro-Ungarico e il Regno d'Italia.</p>
<p>«Il cammino ricorda i tanti che all'epoca della Grande Guerra, hanno attraversato, in cammino, il territorio di confine del Friuli – spiega il direttore artistico <strong>Francesco Accomando</strong> – Migliaia e migliaia da Caporetto a dopo la fine della guerra, truppe in avanzata e in ritirata, militari in rientro dal fronte per la licenza, prigionieri ed ex prigionieri di ritorno, civili fuggiaschi, profughi, deportati… Tutta la narrazione di Oltreconfine parla di questo continuo movimento massivo. Così lo spettacolo ha la forma del camminare, una sorta di rituale laico che coinvolge attori e pubblico nell'atto del ricordare e nello stesso tempo è l'invito a un cammino collettivo da intraprendere per costruire una pace forse mai raggiungibile nella sua pienezza». Nel titolo c'è anche un paradosso, dato che «ci racconta come solo i morti hanno trovato finalmente la pace alle loro sofferenze, mentre per i vivi la guerra della miseria e della fame è continuata ben oltre il termine delle ostilità. Infine ai vivi è concesso il silenzio di una visita al camposanto, ma a loro appartiene anche il silenzio su tutto quello che non hanno voluto o potuto raccontare di quei giorni tremendi».</p>
<p><strong>Per informazioni: tel. 339.4238228</strong></p>`,

  68: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2017/09/OLTRECONFINE-restituzione-teatrale-Ruda.jpg" alt="Restituzione teatrale Ruda" loading="lazy">
<p>Si chiude con una serata speciale alla Caserma Montesanto di <strong>Palmanova</strong> il tour dello spettacolo <strong>"A occhi chiusi e non era solo orrore e spavento"</strong>, la <strong>restituzione teatrale</strong> che chiude il percorso di incontro con le comunità del Friuli Venezia Giulia nell'ambito del progetto <strong>OLTRECONFINE 15I17</strong> curato da <em>Cikale Operose</em>. Dopo aver coinvolto <strong>oltre 700 spettatori</strong> nelle 16 tappe sul territorio, domenica 29 ottobre il lavoro è ospite per l'ultima rappresentazione nelle sale della Caserma con una doppia replica alle 16.30 e alle 18.30.</p>
<p>Diretto da <strong>Francesco Accomando</strong>, il lavoro <strong>"A occhi chiusi e non era solo orrore e spavento"</strong> vede in scena attori non professionisti (Silvio Basile, Anna Bolognese, Bruno Chiaranti, Pia Comoretto, Paolo Da Dalt, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Sergio Pagavino, Simona Schepis, Renato Sclauzero, Bruno Tomasin, Fabio Vidoz) che si sono uniti per dare vita ai ricordi, alle suggestioni, alle fotografie, alle testimonianze raccolte tra i cittadini durante le serate-forum dei mesi scorsi e che comprendono un periodo che va dal giugno 1915 fino ai fatti di Caporetto nell'ottobre del 1917.</p>
<p>Oltre sei mesi di prove con attori non professionisti, serate di confronto con le comunità locali del FVG, un grande collage di storie, sentimenti e aneddoti sulla Grande Guerra vissuta a cavallo tra Italia e Austria. Nei mesi di lavoro si sono incrociate le relazioni degli storici locali e le memorie di singoli cittadini che hanno dato vita una struttura che unisce narrazione e azioni sceniche. Le storie narrate seguiranno l'idea di uno sguardo dal basso, popolare, di gente semplice che viveva a ridosso del confine, rielaborato attraverso i linguaggi della contemporaneità, fatti di parole, musica, immagini evocate e gestualità scenica.</p>
<p>Ingresso libero con prenotazione obbligatoria chiamando il <em>392.0602632 dalle 10 alle 12 e dalle 16 alle 18 fino al giorno dello spettacolo</em> (max 30 persone per recita).</p>
<p><strong>OLTRECONFINE</strong> è un progetto partecipato che ha riunito i cittadini e le associazioni di 17 comuni del FVG: Palmanova come capofila e poi Aiello del Friuli, Bagnaria Arsa, Bicinicco, Campolongo Tapogliano, Castions di Strada, Chiopris Viscone, Gonars, Medea, Romans d'Isonzo, Ruda, San Vito al Torre, Santa Maria La Longa, Torviscosa, Trivignano Udinese, Villesse, Visco. Tutti territori che, nel 1915, si trovarono "presi in mezzo" dalla guerra, essendo a ridosso o sul confine tra l'Impero Austro-Ungarico e il Regno d'Italia.</p>
<p>"Siamo arrivati al momento conclusivo di questa seconda esperienza progettuale di Oltreconfine che avrà luogo nella nostra città – rimarca <strong>Adriana Danielis</strong> vicesindaco di Palmanova, Comune capofila del progetto – Si può già trarre un bilancio positivo su questa diversa modalità del ricordare la nostra storia. Caporetto fu un evento drammatico per le nostre terre che videro l'occupazione di eserciti stranieri per un anno esatto, la prigionia in Austria e Germania, conobbero la fuga e poi l'esodo di parte della comunità e delle amministrazioni. Il Comune di Palmanova trasferì la sua sede a Firenze da dove avvenivano i contatti con i prigionieri e le loro famiglie. Sono queste tragedie umane a segnare le coscienze e a porci con occhi attenti al presente che, come vediamo, tende a ripresentare schemi di comportamento, di fatto mai superati, e a ripresentarsi non appena si oblia la memoria di testimoni diretti e indiretti. Tenere vivi i fatti attraverso il mondo dei vissuti e quindi della gente comune, credo sia il grande merito di questo progetto che agisce sulla doppia dimensione storica e di consapevolezza, prerogativa di un certo teatro e del suo impatto con il pubblico. Al termine di questa esperienza ci organizzeremo subito con tutti i Comuni per dare avvio alla terza e ultima parte di Oltreconfine".</p>
<p>"Oltreconfine – spiega il direttore artistico <strong>Francesco Accomando</strong> – è nato dall'esigenza di creare un immaginario storico, comune e condiviso, di alcuni avvenimenti significativi nella pluralità dei punti di vista e nel superamento di alcune distorsioni, mistificazioni e manomissioni intercorse negli anni successivi. Così possiamo raccogliere, valorizzare e rendere comune un patrimonio di storie emblematiche nel rispetto storico del doppio punto vista italiano e austriaco, contribuendo alla costruzione di una coscienza e di una cultura europea dei territori volte al superamento dei contrasti, dei conflitti e dell'idea stessa di confine".</p>`,

};

  3: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/07/20180711-001-castions.jpg" alt="Castions di Strada passeggiata teatrale" loading="lazy">
<p>Rinviata per maltempo a luglio, la "passeggiata teatrale" nel progetto <strong>OLTRECONFINE 1918/2018</strong> incontra la comunità di <strong>CASTIONS DI STRADA</strong> giovedì 23 agosto. Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 20.30 dalla Chiesa di S. Maria (via del Riposo) e attraverserà strade e campagne avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>L'evento teatrale si presenta come una processione laica, sulla quale il direttore artistico <strong>Francesco Accomando</strong>, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti nella costruzione di una restituzione drammaturgica delle memorie raccolte.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<p>"<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" porterà un vero e toccante coinvolgimento delle comunità a partire dalle strade e dalle piazze, altre 17 tappe fino alla fine di agosto. L'intera comunità dei paesi toccati dalla "processione" laica è invitata a partecipare, per vivere l'emozione di una memoria lontana cent'anni eppure ancora viva nelle famiglie che hanno sofferto il dramma su un confine che è divenuto un fronte cruciale per le sorti della Prima Guerra Mondiale.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita (l'organizzazione consiglia abbigliamento e scarpe comodi). Le passeggiate teatrali si svolgeranno all'aperto, dunque in caso di maltempo gli eventi interessati dovranno essere rinviati. Gli organizzatori declinano qualsiasi responsabilità durante e dopo la manifestazione.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/08/OLTRECONFINE-2018-passeggiata-teatrale-col2.jpg" alt="Oltreconfine 2018 passeggiata teatrale" loading="lazy">
<p>Il progetto triennale <strong>OLTRECONFINE</strong> si chiude nel 2018 con la terza tappa nel percorso attraverso la memoria del primo conflitto mondiale confluisce in un lavoro teatrale per dare vita ai ricordi, alle suggestioni, alle fotografie, alle testimonianze raccolte tra i cittadini durante le serate-forum dei mesi scorsi.</p>
<p>Nei mesi di lavoro si sono incrociate le relazioni degli storici locali e le memorie di singoli cittadini che hanno dato vita una struttura che unisce narrazione e azioni sceniche. Le storie narrate seguiranno l'idea di uno sguardo dal basso, popolare, di gente semplice che viveva a ridosso del confine, rielaborato attraverso i linguaggi della contemporaneità, fatti di parole, musica, immagini evocate e gestualità scenica.</p>
<p><strong>OLTRECONFINE</strong> è un progetto partecipato che ha riunito i cittadini e le associazioni di 17 comuni del FVG: Palmanova (capofila), Aiello del Friuli, Bagnaria Arsa, Bicinicco, Campolongo Tapogliano, Castions di Strada, Chiopris Viscone, Gonars, Medea, Romans D'Isonzo, Ruda, San Vito al Torre, Santa Maria La Longa, Torviscosa, Trivignano Udinese, Villesse, Visco. Tutti territori che, nel 1915, si trovarono "presi in mezzo" dalla guerra, essendo a ridosso o sul confine tra l'Impero Austro-Ungarico e il Regno d'Italia.</p>
<p>«Il cammino ricorda i tanti che all'epoca della Grande Guerra, hanno attraversato, in cammino, il territorio di confine del Friuli – spiega il direttore artistico <strong>Francesco Accomando</strong> – Migliaia e migliaia da Caporetto a dopo la fine della guerra, truppe in avanzata e in ritirata, militari in rientro dal fronte per la licenza, prigionieri ed ex prigionieri di ritorno, civili fuggiaschi, profughi, deportati… Tutta la narrazione di Oltreconfine parla di questo continuo movimento massivo. Così lo spettacolo ha la forma del camminare, una sorta di rituale laico che coinvolge attori e pubblico nell'atto del ricordare e nello stesso tempo è l'invito a un cammino collettivo da intraprendere per costruire una pace forse mai raggiungibile nella sua pienezza». Nel titolo c'è anche un paradosso, dato che «ci racconta come solo i morti hanno trovato finalmente la pace alle loro sofferenze, mentre per i vivi la guerra della miseria e della fame è continuata ben oltre il termine delle ostilità. Infine ai vivi è concesso il silenzio di una visita al camposanto, ma a loro appartiene anche il silenzio su tutto quello che non hanno voluto o potuto raccontare di quei giorni tremendi».</p>
<p><strong>Per informazioni: tel. 339.4238228</strong></p>`,

  4: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/08/20180809-001-s.maria-mereto.jpg" alt="S. Maria la Longa passeggiata teatrale" loading="lazy">
<p>Si avvia alla conclusione il lungo, emozionante percorso della "passeggiata teatrale" nel progetto <strong>OLTRECONFINE 1918/2018</strong>, che giovedì 9 agosto arriva a <strong>S. MARIA LA LONGA</strong>. Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 20.45 dall'ex convento delle Clarisse in località Mereto di Capitolo e attraverserà strade e argini avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>L'evento teatrale si configura come una processione laica, sulla quale il direttore artistico <strong>Francesco Accomando</strong>, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti nella costruzione di una restituzione drammaturgica delle memorie raccolte.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/08/OLTRECONFINE-2018-passeggiata-teatrale-col.jpg" alt="Oltreconfine 2018 passeggiata teatrale" loading="lazy">
<p>L'intera comunità dei paesi toccati dalla "processione" laica è invitata a partecipare, per vivere l'emozione di una memoria lontana cent'anni eppure ancora viva nelle famiglie che hanno sofferto il dramma su un confine che è divenuto un fronte cruciale per le sorti della Prima Guerra Mondiale.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita (l'organizzazione consiglia abbigliamento e scarpe comodi). Le passeggiate teatrali si svolgeranno all'aperto, dunque in caso di maltempo gli eventi interessati dovranno essere rinviati. Gli organizzatori declinano qualsiasi responsabilità durante e dopo la manifestazione.</p>
<p>Il progetto triennale <strong>OLTRECONFINE</strong> si chiude nel 2018 con la terza tappa nel percorso attraverso la memoria del primo conflitto mondiale confluisce in un lavoro teatrale per dare vita ai ricordi, alle suggestioni, alle fotografie, alle testimonianze raccolte tra i cittadini durante le serate-forum dei mesi scorsi. Nei mesi di lavoro si sono incrociate le relazioni degli storici locali e le memorie di singoli cittadini che hanno dato vita una struttura che unisce narrazione e azioni sceniche. Le storie narrate seguiranno l'idea di uno sguardo dal basso, popolare, di gente semplice che viveva a ridosso del confine, rielaborato attraverso i linguaggi della contemporaneità, fatti di parole, musica, immagini evocate e gestualità scenica.</p>
<p><strong>OLTRECONFINE</strong> è un progetto partecipato che ha riunito i cittadini e le associazioni di 17 comuni del FVG: Palmanova (capofila), Aiello del Friuli, Bagnaria Arsa, Bicinicco, Campolongo Tapogliano, Castions di Strada, Chiopris Viscone, Gonars, Medea, Romans D'Isonzo, Ruda, San Vito al Torre, Santa Maria La Longa, Torviscosa, Trivignano Udinese, Villesse, Visco. Tutti territori che, nel 1915, si trovarono "presi in mezzo" dalla guerra, essendo a ridosso o sul confine tra l'Impero Austro-Ungarico e il Regno d'Italia.</p>
<p>«Il cammino ricorda i tanti che all'epoca della Grande Guerra, hanno attraversato, in cammino, il territorio di confine del Friuli – spiega il direttore artistico <strong>Francesco Accomando</strong> – Migliaia e migliaia da Caporetto a dopo la fine della guerra, truppe in avanzata e in ritirata, militari in rientro dal fronte per la licenza, prigionieri ed ex prigionieri di ritorno, civili fuggiaschi, profughi, deportati… Tutta la narrazione di Oltreconfine parla di questo continuo movimento massivo. Così lo spettacolo ha la forma del camminare, una sorta di rituale laico che coinvolge attori e pubblico nell'atto del ricordare e nello stesso tempo è l'invito a un cammino collettivo da intraprendere per costruire una pace forse mai raggiungibile nella sua pienezza». Nel titolo c'è anche un paradosso, dato che «ci racconta come solo i morti hanno trovato finalmente la pace alle loro sofferenze, mentre per i vivi la guerra della miseria e della fame è continuata ben oltre il termine delle ostilità. Infine ai vivi è concesso il silenzio di una visita al camposanto, ma a loro appartiene anche il silenzio su tutto quello che non hanno voluto o potuto raccontare di quei giorni tremendi».</p>
<p><strong>Per informazioni: tel. 339.4238228</strong></p>`,



  5: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/08/OLTRECONFINE-2018-passeggiata-teatrale.jpg" alt="Torviscosa passeggiata teatrale" loading="lazy">
<p>Una nuova tappa nella "passeggiata teatrale" del progetto <strong>OLTRECONFINE 1918/2018</strong>, che lunedì 6 agosto arriva a <strong>TORVISCOSA</strong>. Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 20.45 dalla Chiesa dei SS. Pietro e Paolo in località Malisana e attraverserà strade e argini avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>L'evento teatrale si configura come una processione laica, sulla quale il direttore artistico <strong>Francesco Accomando</strong>, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti nella costruzione di una restituzione drammaturgica delle memorie raccolte.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/08/OLTRECONFINE-2018-passeggiata-teatrale-luna.jpg" alt="Passeggiata teatrale notturna Torviscosa" loading="lazy">
<p>L'intera comunità dei paesi toccati dalla "processione" laica è invitata a partecipare, per vivere l'emozione di una memoria lontana cent'anni eppure ancora viva nelle famiglie che hanno sofferto il dramma su un confine che è divenuto un fronte cruciale per le sorti della Prima Guerra Mondiale.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita (l'organizzazione consiglia abbigliamento e scarpe comodi). Le passeggiate teatrali si svolgeranno all'aperto, dunque in caso di maltempo gli eventi interessati dovranno essere rinviati.</p>
<p><strong>OLTRECONFINE</strong> è un progetto partecipato che ha riunito i cittadini e le associazioni di 17 comuni del FVG: Palmanova (capofila), Aiello del Friuli, Bagnaria Arsa, Bicinicco, Campolongo Tapogliano, Castions di Strada, Chiopris Viscone, Gonars, Medea, Romans D'Isonzo, Ruda, San Vito al Torre, Santa Maria La Longa, Torviscosa, Trivignano Udinese, Villesse, Visco. Tutti territori che, nel 1915, si trovarono "presi in mezzo" dalla guerra, essendo a ridosso o sul confine tra l'Impero Austro-Ungarico e il Regno d'Italia.</p>
<p>«Il cammino ricorda i tanti che all'epoca della Grande Guerra, hanno attraversato, in cammino, il territorio di confine del Friuli – spiega il direttore artistico <strong>Francesco Accomando</strong> – Migliaia e migliaia da Caporetto a dopo la fine della guerra, truppe in avanzata e in ritirata, militari in rientro dal fronte per la licenza, prigionieri ed ex prigionieri di ritorno, civili fuggiaschi, profughi, deportati… Tutta la narrazione di Oltreconfine parla di questo continuo movimento massivo. Così lo spettacolo ha la forma del camminare, una sorta di rituale laico che coinvolge attori e pubblico nell'atto del ricordare e nello stesso tempo è l'invito a un cammino collettivo da intraprendere per costruire una pace forse mai raggiungibile nella sua pienezza». Nel titolo c'è anche un paradosso, dato che «ci racconta come solo i morti hanno trovato finalmente la pace alle loro sofferenze, mentre per i vivi la guerra della miseria e della fame è continuata ben oltre il termine delle ostilità. Infine ai vivi è concesso il silenzio di una visita al camposanto, ma a loro appartiene anche il silenzio su tutto quello che non hanno voluto o potuto raccontare di quei giorni tremendi».</p>
<p><strong>Per informazioni: tel. 339.4238228</strong></p>`,


  6: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/08/OLTRECONFINE-passeggiata-teatrale-Villesse-1.jpg" alt="Romans d'Isonzo passeggiata teatrale recupero" loading="lazy">
<p>La "passeggiata teatrale" si recupera venerdì 3 agosto a <strong>ROMANS D'ISONZO</strong> (dopo il rinvio di giugno per maltempo). Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 20.45 dalla località Versa (via Lauretana) e attraverserà strade e campagne avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>L'evento teatrale si configura come una processione laica, sulla quale il direttore artistico <strong>Francesco Accomando</strong>, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti nella costruzione di una restituzione drammaturgica delle memorie raccolte.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<p>L'intera comunità dei paesi toccati dalla "processione" laica è invitata a partecipare, per vivere l'emozione di una memoria lontana cent'anni eppure ancora viva nelle famiglie che hanno sofferto il dramma su un confine che è divenuto un fronte cruciale per le sorti della Prima Guerra Mondiale. La partecipazione alla passeggiata teatrale è gratuita (l'organizzazione consiglia abbigliamento e scarpe comodi). La passeggiata teatrale si svolge all'aperto, dunque in caso di maltempo l'evento dovrà essere rinviato.</p>
<p><strong>Per informazioni: tel. 339.4238228</strong></p>`,

  7: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/07/OLTRECONFINE-passeggiata-teatrale-Villesse-8.jpg" alt="Bagnaria Arsa passeggiata teatrale" loading="lazy">
<p>Il centenario della Grande Guerra porta la passeggiata teatrale a <strong>BAGNARIA ARSA</strong>. La "passeggiata teatrale" nel progetto <strong>OLTRECONFINE 1918/2018</strong> fa tappa mercoledì 1° agosto. Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 20.45 dalla Chiesa dei SS. Pietro e Paolo e attraverserà strade e campagne avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>L'evento teatrale si configura come una processione laica, sulla quale il direttore artistico <strong>Francesco Accomando</strong>, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti nella costruzione di una restituzione drammaturgica delle memorie raccolte.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<p>L'intera comunità dei paesi toccati dalla "processione" laica è invitata a partecipare. La partecipazione alla passeggiata teatrale è gratuita. La passeggiata teatrale si svolge all'aperto, dunque in caso di maltempo l'evento dovrà essere rinviato.</p>
<p><strong>OLTRECONFINE</strong> è un progetto partecipato che ha riunito i cittadini e le associazioni di 17 comuni del FVG: Palmanova (capofila), Aiello del Friuli, Bagnaria Arsa, Bicinicco, Campolongo Tapogliano, Castions di Strada, Chiopris Viscone, Gonars, Medea, Romans D'Isonzo, Ruda, San Vito al Torre, Santa Maria La Longa, Torviscosa, Trivignano Udinese, Villesse, Visco. Tutti territori che, nel 1915, si trovarono "presi in mezzo" dalla guerra, essendo a ridosso o sul confine tra l'Impero Austro-Ungarico e il Regno d'Italia.</p>
<p>«Il cammino ricorda i tanti che all'epoca della Grande Guerra, hanno attraversato, in cammino, il territorio di confine del Friuli – spiega il direttore artistico <strong>Francesco Accomando</strong> – Migliaia e migliaia da Caporetto a dopo la fine della guerra, truppe in avanzata e in ritirata, militari in rientro dal fronte per la licenza, prigionieri ed ex prigionieri di ritorno, civili fuggiaschi, profughi, deportati… Così lo spettacolo ha la forma del camminare, una sorta di rituale laico che coinvolge attori e pubblico nell'atto del ricordare».</p>
<p><strong>Per informazioni: tel. 339.4238228</strong></p>`,


  8: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/07/OLTRECONFINE-passeggiata-teatrale-Villesse-1.jpg" alt="Aiello del Friuli passeggiata teatrale" loading="lazy">
<p>Prosegue l'intenso percorso della "passeggiata teatrale" nel progetto <strong>OLTRECONFINE 1918/2018</strong>, che lunedì 30 luglio fa tappa ad <strong>AIELLO DEL FRIULI</strong>. Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 20.45 dalla Piazza principale e attraverserà strade e campagne avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>L'evento teatrale si configura come una processione laica, sulla quale il direttore artistico <strong>Francesco Accomando</strong>, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti nella costruzione di una restituzione drammaturgica delle memorie raccolte.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<p>L'intera comunità dei paesi toccati dalla "processione" laica è invitata a partecipare, per vivere l'emozione di una memoria lontana cent'anni eppure ancora viva nelle famiglie che hanno sofferto il dramma su un confine che è divenuto un fronte cruciale per le sorti della Prima Guerra Mondiale. La partecipazione alla passeggiata teatrale è gratuita. La passeggiata teatrale si svolge all'aperto, dunque in caso di maltempo l'evento dovrà essere rinviato.</p>
<p>«Il cammino ricorda i tanti che all'epoca della Grande Guerra, hanno attraversato, in cammino, il territorio di confine del Friuli – spiega il direttore artistico <strong>Francesco Accomando</strong> – Migliaia e migliaia da Caporetto a dopo la fine della guerra, truppe in avanzata e in ritirata, militari in rientro dal fronte per la licenza, prigionieri ed ex prigionieri di ritorno, civili fuggiaschi, profughi, deportati… Così lo spettacolo ha la forma del camminare, una sorta di rituale laico che coinvolge attori e pubblico nell'atto del ricordare».</p>
<p><strong>Per informazioni: tel. 339.4238228</strong></p>`,

  9: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/07/OLTRECONFINE-Bicinicco-passeggiata-teatrale-2.jpg" alt="Trivignano Udinese passeggiata teatrale" loading="lazy">
<p>Prosegue l'intenso percorso della "passeggiata teatrale" nel progetto <strong>OLTRECONFINE 1918/2018</strong>, che mercoledì 25 luglio fa tappa a <strong>TRIVIGNANO UDINESE</strong>. Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 20.45 dalla Chiesa parrocchiale e attraverserà strade e campagne avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>L'evento teatrale si configura come una processione laica, sulla quale il direttore artistico <strong>Francesco Accomando</strong>, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti nella costruzione di una restituzione drammaturgica delle memorie raccolte.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno si sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<p>L'intera comunità è invitata a partecipare. La partecipazione alla passeggiata teatrale è gratuita. La passeggiata teatrale si svolge all'aperto, dunque in caso di maltempo l'evento dovrà essere rinviato.</p>
<p>«Il cammino ricorda i tanti che all'epoca della Grande Guerra, hanno attraversato, in cammino, il territorio di confine del Friuli – spiega il direttore artistico <strong>Francesco Accomando</strong> – Migliaia e migliaia da Caporetto a dopo la fine della guerra, truppe in avanzata e in ritirata, militari in rientro dal fronte per la licenza, prigionieri ed ex prigionieri di ritorno, civili fuggiaschi, profughi, deportati… Così lo spettacolo ha la forma del camminare, una sorta di rituale laico che coinvolge attori e pubblico nell'atto del ricordare».</p>
<p><strong>Per informazioni: tel. 339.4238228</strong></p>`,


  10: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/07/OLTRECONFINE-Bicinicco-passeggiata-teatrale.jpg" alt="Ruda passeggiata teatrale" loading="lazy">
<p>Prosegue l'intenso percorso compiuto dalla "passeggiata teatrale" nel progetto <strong>OLTRECONFINE 1918/2018</strong>, che lunedì 23 luglio fa tappa a <strong>RUDA</strong>. Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 21 da Piazza Libertà e attraverserà strade e campagne avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>L'evento teatrale si presenta come una processione laica, sulla quale il direttore artistico <strong>Francesco Accomando</strong>, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti nella costruzione di una restituzione drammaturgica delle memorie raccolte.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno di sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<p>"<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" porterà un vero e toccante coinvolgimento delle comunità a partire dalle strade e dalle piazze, altre 17 tappe fino alla fine di agosto. L'intera comunità dei paesi toccati dalla "processione" laica è invitata a partecipare, per vivere l'emozione di una memoria lontana cent'anni eppure ancora viva nelle famiglie che hanno sofferto il dramma su un confine che è divenuto un fronte cruciale per le sorti della Prima Guerra Mondiale.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita (l'organizzazione consiglia abbigliamento e scarpe comodi). Le passeggiate teatrali si svolgeranno all'aperto, dunque in caso di maltempo gli eventi interessati dovranno essere rinviati. Gli organizzatori declinano qualsiasi responsabilità durante e dopo la manifestazione.</p>
<p>Il progetto triennale <strong>OLTRECONFINE</strong> si chiude nel 2018 con la terza tappa nel percorso attraverso la memoria del primo conflitto mondiale confluisce in un lavoro teatrale per dare vita ai ricordi, alle suggestioni, alle fotografie, alle testimonianze raccolte tra i cittadini durante le serate-forum dei mesi scorsi. Nei mesi di lavoro si sono incrociate le relazioni degli storici locali e le memorie di singoli cittadini che hanno dato vita una struttura che unisce narrazione e azioni sceniche. Le storie narrate seguiranno l'idea di uno sguardo dal basso, popolare, di gente semplice che viveva a ridosso del confine, rielaborato attraverso i linguaggi della contemporaneità, fatti di parole, musica, immagini evocate e gestualità scenica.</p>
<p><strong>OLTRECONFINE</strong> è un progetto partecipato che ha riunito i cittadini e le associazioni di 17 comuni del FVG: Palmanova (capofila), Aiello del Friuli, Bagnaria Arsa, Bicinicco, Campolongo Tapogliano, Castions di Strada, Chiopris Viscone, Gonars, Medea, Romans D'Isonzo, Ruda, San Vito al Torre, Santa Maria La Longa, Torviscosa, Trivignano Udinese, Villesse, Visco. Tutti territori che, nel 1915, si trovarono "presi in mezzo" dalla guerra, essendo a ridosso o sul confine tra l'Impero Austro-Ungarico e il Regno d'Italia.</p>
<p>«Il cammino ricorda i tanti che all'epoca della Grande Guerra, hanno attraversato, in cammino, il territorio di confine del Friuli – spiega il direttore artistico <strong>Francesco Accomando</strong> – Migliaia e migliaia da Caporetto a dopo la fine della guerra, truppe in avanzata e in ritirata, militari in rientro dal fronte per la licenza, prigionieri ed ex prigionieri di ritorno, civili fuggiaschi, profughi, deportati… Tutta la narrazione di Oltreconfine parla di questo continuo movimento massivo. Così lo spettacolo ha la forma del camminare, una sorta di rituale laico che coinvolge attori e pubblico nell'atto del ricordare e nello stesso tempo è l'invito a un cammino collettivo da intraprendere per costruire una pace forse mai raggiungibile nella sua pienezza». Nel titolo c'è anche un paradosso, dato che «ci racconta come solo i morti hanno trovato finalmente la pace alle loro sofferenze, mentre per i vivi la guerra della miseria e della fame è continuata ben oltre il termine delle ostilità. Infine ai vivi è concesso il silenzio di una visita al camposanto, ma a loro appartiene anche il silenzio su tutto quello che non hanno voluto o potuto raccontare di quei giorni tremendi».</p>
<p><strong>Per informazioni > tel. 339.4238228</strong></p>`,

  11: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/07/OLTRECONFINE-villesse.jpg" alt="Villesse passeggiata teatrale" loading="lazy">
<p>Prosegue l'intenso percorso compiuto dalla "passeggiata teatrale" nel progetto <strong>OLTRECONFINE 1918/2018</strong>, che mercoledì 18 luglio fa tappa a <strong>VILLESSE</strong>. Il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 21 dalla Cappella Beato Carlo d'Asburgo e attraverserà strade e campagne avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>L'evento teatrale si presenta come una processione laica, sulla quale il direttore artistico <strong>Francesco Accomando</strong>, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti nella costruzione di una restituzione drammaturgica delle memorie raccolte.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno di sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/07/OLTRECONFINE-2018-passeggiata-teatrale-Campolongo-Tapogliano.jpg" alt="Passeggiata teatrale Campolongo" loading="lazy">
<p>"<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" porterà un vero e toccante coinvolgimento delle comunità a partire dalle strade e dalle piazze, altre 17 tappe fino alla fine di agosto. L'intera comunità dei paesi toccati dalla "processione" laica è invitata a partecipare, per vivere l'emozione di una memoria lontana cent'anni eppure ancora viva nelle famiglie che hanno sofferto il dramma su un confine che è divenuto un fronte cruciale per le sorti della Prima Guerra Mondiale.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita (l'organizzazione consiglia abbigliamento e scarpe comodi). Le passeggiate teatrali si svolgeranno all'aperto, dunque in caso di maltempo gli eventi interessati dovranno essere rinviati. Gli organizzatori declinano qualsiasi responsabilità durante e dopo la manifestazione.</p>
<p>Il progetto triennale <strong>OLTRECONFINE</strong> si chiude nel 2018 con la terza tappa nel percorso attraverso la memoria del primo conflitto mondiale confluisce in un lavoro teatrale per dare vita ai ricordi, alle suggestioni, alle fotografie, alle testimonianze raccolte tra i cittadini durante le serate-forum dei mesi scorsi. Nei mesi di lavoro si sono incrociate le relazioni degli storici locali e le memorie di singoli cittadini che hanno dato vita una struttura che unisce narrazione e azioni sceniche. Le storie narrate seguiranno l'idea di uno sguardo dal basso, popolare, di gente semplice che viveva a ridosso del confine, rielaborato attraverso i linguaggi della contemporaneità, fatti di parole, musica, immagini evocate e gestualità scenica.</p>
<p><strong>OLTRECONFINE</strong> è un progetto partecipato che ha riunito i cittadini e le associazioni di 17 comuni del FVG: Palmanova (capofila), Aiello del Friuli, Bagnaria Arsa, Bicinicco, Campolongo Tapogliano, Castions di Strada, Chiopris Viscone, Gonars, Medea, Romans D'Isonzo, Ruda, San Vito al Torre, Santa Maria La Longa, Torviscosa, Trivignano Udinese, Villesse, Visco. Tutti territori che, nel 1915, si trovarono "presi in mezzo" dalla guerra, essendo a ridosso o sul confine tra l'Impero Austro-Ungarico e il Regno d'Italia.</p>
<p>«Il cammino ricorda i tanti che all'epoca della Grande Guerra, hanno attraversato, in cammino, il territorio di confine del Friuli – spiega il direttore artistico <strong>Francesco Accomando</strong> – Migliaia e migliaia da Caporetto a dopo la fine della guerra, truppe in avanzata e in ritirata, militari in rientro dal fronte per la licenza, prigionieri ed ex prigionieri di ritorno, civili fuggiaschi, profughi, deportati… Tutta la narrazione di Oltreconfine parla di questo continuo movimento massivo. Così lo spettacolo ha la forma del camminare, una sorta di rituale laico che coinvolge attori e pubblico nell'atto del ricordare e nello stesso tempo è l'invito a un cammino collettivo da intraprendere per costruire una pace forse mai raggiungibile nella sua pienezza». Nel titolo c'è anche un paradosso, dato che «ci racconta come solo i morti hanno trovato finalmente la pace alle loro sofferenze, mentre per i vivi la guerra della miseria e della fame è continuata ben oltre il termine delle ostilità. Infine ai vivi è concesso il silenzio di una visita al camposanto, ma a loro appartiene anche il silenzio su tutto quello che non hanno voluto o potuto raccontare di quei giorni tremendi».</p>
<p><strong>Per informazioni  >  tel. 339.4238228</strong></p>`,

  15: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/07/oltreconfine-bicinicco.jpg" alt="Bicinicco passeggiata teatrale" loading="lazy">
<p>Dopo le prime cinque tappe, l'intensa e coinvolgente "passeggiata teatrale" del progetto <strong>OLTRECONFINE 1918/2018</strong> fa tappa a <strong>Bicinicco</strong>. Mercoledì 4 luglio il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 21.15 dalla Chiesa di S. Giorgio e attraverserà strade e campagne avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>L'evento teatrale si presenta come una processione laica, sulla quale il direttore artistico <strong>Francesco Accomando</strong>, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti nella costruzione di una restituzione drammaturgica delle memorie raccolte.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno di sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/06/OLTRECONFINE-passeggiata-teatrale-1.jpg" alt="Passeggiata teatrale" loading="lazy">
<p>"<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" porterà un vero e toccante coinvolgimento delle comunità a partire dalle strade e dalle piazze, altre 17 tappe fino alla fine di agosto. L'intera comunità dei paesi toccati dalla "processione" laica è invitata a partecipare, per vivere l'emozione di una memoria lontana cent'anni eppure ancora viva nelle famiglie che hanno sofferto il dramma su un confine che è divenuto un fronte cruciale per le sorti della Prima Guerra Mondiale.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita (l'organizzazione consiglia abbigliamento e scarpe comodi). Le passeggiate teatrali si svolgeranno all'aperto, dunque in caso di maltempo gli eventi interessati dovranno essere rinviati. Gli organizzatori declinano qualsiasi responsabilità durante e dopo la manifestazione.</p>
<p>Il progetto triennale <strong>OLTRECONFINE</strong> si chiude nel 2018 con la terza tappa nel percorso attraverso la memoria del primo conflitto mondiale confluisce in un lavoro teatrale per dare vita ai ricordi, alle suggestioni, alle fotografie, alle testimonianze raccolte tra i cittadini durante le serate-forum dei mesi scorsi. Nei mesi di lavoro si sono incrociate le relazioni degli storici locali e le memorie di singoli cittadini che hanno dato vita una struttura che unisce narrazione e azioni sceniche. Le storie narrate seguiranno l'idea di uno sguardo dal basso, popolare, di gente semplice che viveva a ridosso del confine, rielaborato attraverso i linguaggi della contemporaneità, fatti di parole, musica, immagini evocate e gestualità scenica.</p>
<p><strong>OLTRECONFINE</strong> è un progetto partecipato che ha riunito i cittadini e le associazioni di 17 comuni del FVG: Palmanova (capofila), Aiello del Friuli, Bagnaria Arsa, Bicinicco, Campolongo Tapogliano, Castions di Strada, Chiopris Viscone, Gonars, Medea, Romans D'Isonzo, Ruda, San Vito al Torre, Santa Maria La Longa, Torviscosa, Trivignano Udinese, Villesse, Visco. Tutti territori che, nel 1915, si trovarono "presi in mezzo" dalla guerra, essendo a ridosso o sul confine tra l'Impero Austro-Ungarico e il Regno d'Italia.</p>
<p>«Il cammino ricorda i tanti che all'epoca della Grande Guerra, hanno attraversato, in cammino, il territorio di confine del Friuli – spiega il direttore artistico <strong>Francesco Accomando</strong> – Migliaia e migliaia da Caporetto a dopo la fine della guerra, truppe in avanzata e in ritirata, militari in rientro dal fronte per la licenza, prigionieri ed ex prigionieri di ritorno, civili fuggiaschi, profughi, deportati… Tutta la narrazione di Oltreconfine parla di questo continuo movimento massivo. Così lo spettacolo ha la forma del camminare, una sorta di rituale laico che coinvolge attori e pubblico nell'atto del ricordare e nello stesso tempo è l'invito a un cammino collettivo da intraprendere per costruire una pace forse mai raggiungibile nella sua pienezza». Nel titolo c'è anche un paradosso, dato che «ci racconta come solo i morti hanno trovato finalmente la pace alle loro sofferenze, mentre per i vivi la guerra della miseria e della fame è continuata ben oltre il termine delle ostilità. Infine ai vivi è concesso il silenzio di una visita al camposanto, ma a loro appartiene anche il silenzio su tutto quello che non hanno voluto o potuto raccontare di quei giorni tremendi».</p>
<p><strong>Per informazioni > tel. 339.4238228</strong></p>`,

};

  14: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/07/oltreconfine-passeggiata-teatrale-Gonars-5.jpg" alt="Visco passeggiata teatrale" loading="lazy">
<p>Dopo le prime serate, l'intensa e coinvolgente "passeggiata teatrale" del progetto <strong>OLTRECONFINE 1918/2018</strong> fa tappa a <strong>Visco</strong>. Lunedì 9 luglio il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 21.00 da Piazza Ledra e attraverserà strade e campagne avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>L'evento teatrale si presenta come una processione laica, sulla quale il direttore artistico <strong>Francesco Accomando</strong>, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti nella costruzione di una restituzione drammaturgica delle memorie raccolte.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno di sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<p>"<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" porterà un vero e toccante coinvolgimento delle comunità a partire dalle strade e dalle piazze, altre 17 tappe fino alla fine di agosto. L'intera comunità dei paesi toccati dalla "processione" laica è invitata a partecipare, per vivere l'emozione di una memoria lontana cent'anni eppure ancora viva nelle famiglie che hanno sofferto il dramma su un confine che è divenuto un fronte cruciale per le sorti della Prima Guerra Mondiale.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita (l'organizzazione consiglia abbigliamento e scarpe comodi). Le passeggiate teatrali si svolgeranno all'aperto, dunque in caso di maltempo gli eventi interessati dovranno essere rinviati. Gli organizzatori declinano qualsiasi responsabilità durante e dopo la manifestazione.</p>
<p>Il progetto triennale <strong>OLTRECONFINE</strong> si chiude nel 2018 con la terza tappa nel percorso attraverso la memoria del primo conflitto mondiale confluisce in un lavoro teatrale per dare vita ai ricordi, alle suggestioni, alle fotografie, alle testimonianze raccolte tra i cittadini durante le serate-forum dei mesi scorsi. Nei mesi di lavoro si sono incrociate le relazioni degli storici locali e le memorie di singoli cittadini che hanno dato vita una struttura che unisce narrazione e azioni sceniche. Le storie narrate seguiranno l'idea di uno sguardo dal basso, popolare, di gente semplice che viveva a ridosso del confine, rielaborato attraverso i linguaggi della contemporaneità, fatti di parole, musica, immagini evocate e gestualità scenica.</p>
<p><strong>OLTRECONFINE</strong> è un progetto partecipato che ha riunito i cittadini e le associazioni di 17 comuni del FVG: Palmanova (capofila), Aiello del Friuli, Bagnaria Arsa, Bicinicco, Campolongo Tapogliano, Castions di Strada, Chiopris Viscone, Gonars, Medea, Romans D'Isonzo, Ruda, San Vito al Torre, Santa Maria La Longa, Torviscosa, Trivignano Udinese, Villesse, Visco. Tutti territori che, nel 1915, si trovarono "presi in mezzo" dalla guerra, essendo a ridosso o sul confine tra l'Impero Austro-Ungarico e il Regno d'Italia.</p>
<p>«Il cammino ricorda i tanti che all'epoca della Grande Guerra, hanno attraversato, in cammino, il territorio di confine del Friuli – spiega il direttore artistico <strong>Francesco Accomando</strong> – Migliaia e migliaia da Caporetto a dopo la fine della guerra, truppe in avanzata e in ritirata, militari in rientro dal fronte per la licenza, prigionieri ed ex prigionieri di ritorno, civili fuggiaschi, profughi, deportati… Tutta la narrazione di Oltreconfine parla di questo continuo movimento massivo. Così lo spettacolo ha la forma del camminare, una sorta di rituale laico che coinvolge attori e pubblico nell'atto del ricordare e nello stesso tempo è l'invito a un cammino collettivo da intraprendere per costruire una pace forse mai raggiungibile nella sua pienezza». Nel titolo c'è anche un paradosso, dato che «ci racconta come solo i morti hanno trovato finalmente la pace alle loro sofferenze, mentre per i vivi la guerra della miseria e della fame è continuata ben oltre il termine delle ostilità. Infine ai vivi è concesso il silenzio di una visita al camposanto, ma a loro appartiene anche il silenzio su tutto quello che non hanno voluto o potuto raccontare di quei giorni tremendi».</p>
<p><strong>Per informazioni: tel. 339.4238228</strong></p>`,

  16: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/06/campolongo.jpg" alt="Campolongo Tapogliano passeggiata teatrale" loading="lazy">
<p>Dopo le prime tre tappe, l'intensa e coinvolgente "passeggiata teatrale" del progetto <strong>OLTRECONFINE 1918/2018</strong> arriva a <strong>Campolongo Tapogliano</strong>. Lunedì 2 luglio il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 21.15 dalla Chiesa di S. Maria Assunta in località Cavenzano e attraverserà strade e argini avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>L'evento teatrale si presenta come una processione laica, sulla quale il direttore artistico <strong>Francesco Accomando</strong>, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti nella costruzione di una restituzione drammaturgica delle memorie raccolte.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno di sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/06/OLTRECONFINE-passeggiata-teatrale-1.jpg" alt="Passeggiata teatrale Campolongo" loading="lazy">
<p>"<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" porterà un vero e toccante coinvolgimento delle comunità a partire dalle strade e dalle piazze, altre 17 tappe fino alla fine di agosto. L'intera comunità dei paesi toccati dalla "processione" laica è invitata a partecipare, per vivere l'emozione di una memoria lontana cent'anni eppure ancora viva nelle famiglie che hanno sofferto il dramma su un confine che è divenuto un fronte cruciale per le sorti della Prima Guerra Mondiale.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita (l'organizzazione consiglia abbigliamento e scarpe comodi). Le passeggiate teatrali si svolgeranno all'aperto, dunque in caso di maltempo gli eventi interessati dovranno essere rinviati. Gli organizzatori declinano qualsiasi responsabilità durante e dopo la manifestazione.</p>
<p>Il progetto triennale <strong>OLTRECONFINE</strong> si chiude nel 2018 con la terza tappa nel percorso attraverso la memoria del primo conflitto mondiale confluisce in un lavoro teatrale per dare vita ai ricordi, alle suggestioni, alle fotografie, alle testimonianze raccolte tra i cittadini durante le serate-forum dei mesi scorsi. Nei mesi di lavoro si sono incrociate le relazioni degli storici locali e le memorie di singoli cittadini che hanno dato vita una struttura che unisce narrazione e azioni sceniche. Le storie narrate seguiranno l'idea di uno sguardo dal basso, popolare, di gente semplice che viveva a ridosso del confine, rielaborato attraverso i linguaggi della contemporaneità, fatti di parole, musica, immagini evocate e gestualità scenica.</p>
<p><strong>OLTRECONFINE</strong> è un progetto partecipato che ha riunito i cittadini e le associazioni di 17 comuni del FVG: Palmanova (capofila), Aiello del Friuli, Bagnaria Arsa, Bicinicco, Campolongo Tapogliano, Castions di Strada, Chiopris Viscone, Gonars, Medea, Romans D'Isonzo, Ruda, San Vito al Torre, Santa Maria La Longa, Torviscosa, Trivignano Udinese, Villesse, Visco. Tutti territori che, nel 1915, si trovarono "presi in mezzo" dalla guerra, essendo a ridosso o sul confine tra l'Impero Austro-Ungarico e il Regno d'Italia.</p>
<p>«Il cammino ricorda i tanti che all'epoca della Grande Guerra, hanno attraversato, in cammino, il territorio di confine del Friuli – spiega il direttore artistico <strong>Francesco Accomando</strong> – Migliaia e migliaia da Caporetto a dopo la fine della guerra, truppe in avanzata e in ritirata, militari in rientro dal fronte per la licenza, prigionieri ed ex prigionieri di ritorno, civili fuggiaschi, profughi, deportati… Tutta la narrazione di Oltreconfine parla di questo continuo movimento massivo. Così lo spettacolo ha la forma del camminare, una sorta di rituale laico che coinvolge attori e pubblico nell'atto del ricordare e nello stesso tempo è l'invito a un cammino collettivo da intraprendere per costruire una pace forse mai raggiungibile nella sua pienezza». Nel titolo c'è anche un paradosso, dato che «ci racconta come solo i morti hanno trovato finalmente la pace alle loro sofferenze, mentre per i vivi la guerra della miseria e della fame è continuata ben oltre il termine delle ostilità. Infine ai vivi è concesso il silenzio di una visita al camposanto, ma a loro appartiene anche il silenzio su tutto quello che non hanno voluto o potuto raccontare di quei giorni tremendi».</p>
<p><strong>Per informazioni > tel. 339.4238228</strong></p>`,

};

  17: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/06/OLTRECONFINE-passeggiata-teatrale-1.jpg" alt="Gonars passeggiata teatrale" loading="lazy">
<p>Dopo le prime tre tappe, l'intensa e coinvolgente "passeggiata teatrale" del progetto <strong>OLTRECONFINE 1918/2018</strong> arriva a <strong>Gonars</strong>. Mercoledì 27 giugno il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 21.15 dalla Scuola dell'Infanzia "Chiara e Federico" (via Molini) e attraverserà strade e argini avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>L'evento teatrale si presenta come una processione laica, sulla quale il direttore artistico <strong>Francesco Accomando</strong>, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti nella costruzione di una restituzione drammaturgica delle memorie raccolte.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno di sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<p>"<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" porterà un vero e toccante coinvolgimento delle comunità a partire dalle strade e dalle piazze, altre 17 tappe fino alla fine di agosto. L'intera comunità dei paesi toccati dalla "processione" laica è invitata a partecipare, per vivere l'emozione di una memoria lontana cent'anni eppure ancora viva nelle famiglie che hanno sofferto il dramma su un confine che è divenuto un fronte cruciale per le sorti della Prima Guerra Mondiale.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita (l'organizzazione consiglia abbigliamento e scarpe comodi). Le passeggiate teatrali si svolgeranno all'aperto, dunque in caso di maltempo gli eventi interessati dovranno essere rinviati. Gli organizzatori declinano qualsiasi responsabilità durante e dopo la manifestazione.</p>
<p>Il progetto triennale <strong>OLTRECONFINE</strong> si chiude nel 2018 con la terza tappa nel percorso attraverso la memoria del primo conflitto mondiale confluisce in un lavoro teatrale per dare vita ai ricordi, alle suggestioni, alle fotografie, alle testimonianze raccolte tra i cittadini durante le serate-forum dei mesi scorsi. Nei mesi di lavoro si sono incrociate le relazioni degli storici locali e le memorie di singoli cittadini che hanno dato vita una struttura che unisce narrazione e azioni sceniche. Le storie narrate seguiranno l'idea di uno sguardo dal basso, popolare, di gente semplice che viveva a ridosso del confine, rielaborato attraverso i linguaggi della contemporaneità, fatti di parole, musica, immagini evocate e gestualità scenica.</p>
<p><strong>OLTRECONFINE</strong> è un progetto partecipato che ha riunito i cittadini e le associazioni di 17 comuni del FVG: Palmanova (capofila), Aiello del Friuli, Bagnaria Arsa, Bicinicco, Campolongo Tapogliano, Castions di Strada, Chiopris Viscone, Gonars, Medea, Romans D'Isonzo, Ruda, San Vito al Torre, Santa Maria La Longa, Torviscosa, Trivignano Udinese, Villesse, Visco. Tutti territori che, nel 1915, si trovarono "presi in mezzo" dalla guerra, essendo a ridosso o sul confine tra l'Impero Austro-Ungarico e il Regno d'Italia.</p>
<p>«Il cammino ricorda i tanti che all'epoca della Grande Guerra, hanno attraversato, in cammino, il territorio di confine del Friuli – spiega il direttore artistico <strong>Francesco Accomando</strong> – Migliaia e migliaia da Caporetto a dopo la fine della guerra, truppe in avanzata e in ritirata, militari in rientro dal fronte per la licenza, prigionieri ed ex prigionieri di ritorno, civili fuggiaschi, profughi, deportati… Tutta la narrazione di Oltreconfine parla di questo continuo movimento massivo. Così lo spettacolo ha la forma del camminare, una sorta di rituale laico che coinvolge attori e pubblico nell'atto del ricordare e nello stesso tempo è l'invito a un cammino collettivo da intraprendere per costruire una pace forse mai raggiungibile nella sua pienezza». Nel titolo c'è anche un paradosso, dato che «ci racconta come solo i morti hanno trovato finalmente la pace alle loro sofferenze, mentre per i vivi la guerra della miseria e della fame è continuata ben oltre il termine delle ostilità. Infine ai vivi è concesso il silenzio di una visita al camposanto, ma a loro appartiene anche il silenzio su tutto quello che non hanno voluto o potuto raccontare di quei giorni tremendi».</p>
<p><strong>Per informazioni: tel. 339.4238228</strong></p>`,

};

  18: `<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/06/romans-versa.jpg" alt="Romans d'Isonzo Versa passeggiata teatrale" loading="lazy">
<p>Dopo le prime due tappe, l'intensa e coinvolgente "passeggiata teatrale" del progetto <strong>OLTRECONFINE 1918/2018</strong> arriva a <strong>Romans d'Isonzo</strong>. Lunedì 25 giugno il percorso teatrale "<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" prenderà le mosse alle 21.15 dalla località Versa (via Lauretana) e attraverserà strade e argini avvolgendo il filo rosso della memoria a 100 anni dalla fine della Grande Guerra.</p>
<p>L'evento teatrale si configura come una processione laica, sulla quale il direttore artistico <strong>Francesco Accomando</strong>, Giampaolo Fioretti e Gianni Russo di <strong>Cikale Operose</strong> hanno lavorato per due mesi con un gruppo di attori non professionisti nella costruzione di una restituzione drammaturgica delle memorie raccolte.</p>
<p>Ad accompagnare la passeggiata, i racconti e le letture dalla Grande Guerra saranno interpretati da Silvio Basile, Anna Bolognese, Bruno Chiaranti, Silvia D'Ambrosio, Rossana Di Tommaso, Rinaldo Fantino, Gabriella Ferigutti, Romeo Mischis, Renato Sclauzero, Bruno Tomasin e Fabio Vidoz, già protagonisti nella precedente edizione, ai quali quest'anno di sono aggiunti Franco D'Ambrosio, Sandra Mansutti, Alessio Michelin, Andrea Nicola, Massimiliana Olivo e Francesco Ursella.</p>
<img src="https://www.oltreconfine-ww1.eu/wp-content/uploads/2018/06/OLTRECONFINE-passeggiata-teatrale-1.jpg" alt="Passeggiata teatrale Gonars" loading="lazy">
<p>"<strong>In cammino: la pace dei morti, il silenzio dei vivi</strong>" porterà un vero e toccante coinvolgimento delle comunità a partire dalle strade e dalle piazze, altre 17 tappe fino alla fine di agosto. L'intera comunità dei paesi toccati dalla "processione" laica è invitata a partecipare, per vivere l'emozione di una memoria lontana cent'anni eppure ancora viva nelle famiglie che hanno sofferto il dramma su un confine che è divenuto un fronte cruciale per le sorti della Prima Guerra Mondiale.</p>
<p>La partecipazione alla passeggiata teatrale è gratuita (l'organizzazione consiglia abbigliamento e scarpe comodi). Le passeggiate teatrali si svolgeranno all'aperto, dunque in caso di maltempo gli eventi interessati dovranno essere rinviati. Gli organizzatori declinano qualsiasi responsabilità durante e dopo la manifestazione.</p>
<p>Il progetto triennale <strong>OLTRECONFINE</strong> si chiude nel 2018 con la terza tappa nel percorso attraverso la memoria del primo conflitto mondiale confluisce in un lavoro teatrale per dare vita ai ricordi, alle suggestioni, alle fotografie, alle testimonianze raccolte tra i cittadini durante le serate-forum dei mesi scorsi. Nei mesi di lavoro si sono incrociate le relazioni degli storici locali e le memorie di singoli cittadini che hanno dato vita una struttura che unisce narrazione e azioni sceniche. Le storie narrate seguiranno l'idea di uno sguardo dal basso, popolare, di gente semplice che viveva a ridosso del confine, rielaborato attraverso i linguaggi della contemporaneità, fatti di parole, musica, immagini evocate e gestualità scenica.</p>
<p><strong>OLTRECONFINE</strong> è un progetto partecipato che ha riunito i cittadini e le associazioni di 17 comuni del FVG: Palmanova (capofila), Aiello del Friuli, Bagnaria Arsa, Bicinicco, Campolongo Tapogliano, Castions di Strada, Chiopris Viscone, Gonars, Medea, Romans D'Isonzo, Ruda, San Vito al Torre, Santa Maria La Longa, Torviscosa, Trivignano Udinese, Villesse, Visco. Tutti territori che, nel 1915, si trovarono "presi in mezzo" dalla guerra, essendo a ridosso o sul confine tra l'Impero Austro-Ungarico e il Regno d'Italia.</p>
<p>«Il cammino ricorda i tanti che all'epoca della Grande Guerra, hanno attraversato, in cammino, il territorio di confine del Friuli – spiega il direttore artistico <strong>Francesco Accomando</strong> – Migliaia e migliaia da Caporetto a dopo la fine della guerra, truppe in avanzata e in ritirata, militari in rientro dal fronte per la licenza, prigionieri ed ex prigionieri di ritorno, civili fuggiaschi, profughi, deportati… Tutta la narrazione di Oltreconfine parla di questo continuo movimento massivo. Così lo spettacolo ha la forma del camminare, una sorta di rituale laico che coinvolge attori e pubblico nell'atto del ricordare e nello stesso tempo è l'invito a un cammino collettivo da intraprendere per costruire una pace forse mai raggiungibile nella sua pienezza». Nel titolo c'è anche un paradosso, dato che «ci racconta come solo i morti hanno trovato finalmente la pace alle loro sofferenze, mentre per i vivi la guerra della miseria e della fame è continuata ben oltre il termine delle ostilità. Infine ai vivi è concesso il silenzio di una visita al camposanto, ma a loro appartiene anche il silenzio su tutto quello che non hanno voluto o potuto raccontare di quei giorni tremendi».</p>
<p><strong>Per informazioni: tel. 339.4238228</strong></p>`,

};
